### ISSUE TITLE
verify_certs:false in client-options not taken into account for benchmark-only

### ISSUE THREAD

**Issue by arthurlogilab** [elastic/rally#1188]
**Rally version** (get with `esrally --version`):

```
esrally --version
esrally 2.0.4
```

**Invoked command**:

```
esrally race --pipeline=benchmark-only --target-hosts=localhost:9200 --track=percolator --include-tasks=delete-index,create-index,index,percolator_with_content_google --kill-running-processes --client-options="use_ssl:true,verify_certs:false,basic_auth_user:'elastic',basic_auth_password:'xxx'"
```

**Configuration file (located in `~/.rally/rally.ini`))**: default version

**JVM version**: n/a

**OS version**: Ubuntu python3.8

**Description of the problem including expected versus actual behavior**:

Rally stalls, in logs ssl check errors show up : 

```
During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/esrally/actor.py", line 85, in guard
    return f(self, msg, sender)

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/esrally/racecontrol.py", line 100, in receiveMsg_Setup
    self.coordinator.setup(sources=msg.sources)

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/esrally/racecontrol.py", line 179, in setup
    distribution_version = mechanic.cluster_distribution_version(self.cfg)

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/esrally/mechanic/mechanic.py", line 265, in cluster_distribution_version
    return es.info()["version"]["number"]

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 284, in info
    return self.transport.perform_request(

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/elasticsearch/transport.py", line 390, in perform_request
    raise e

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(

  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 255, in perform_request
    raise SSLError("N/A", str(e), e)

elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123))

```

`curl -u "elastic:$PASSWORD" -k "https://localhost:9200"` works

**Comment by DJRickyB** [comment]
Hi @arthurlogilab, thanks for your report.  I am not able to reproduce this locally.  

Can you please ensure the log message you are receiving is from the run you are triggering with the above client options?  It may be easiest to simply delete .rally/logs/rally.log and run it again.

**Comment by arthurlogilab** [comment]
@DJRickyB Thanks for taking a look at this ! 

Yes I can confirm by deleting the log and relaunching the race. 

This is the beginning of the log : (then it loops on the cert traceback)

```
2021-02-17 08:31:10,929 -not-actor-/PID:73303 esrally.rally INFO Race id [9a290818-123b-42e9-a716-2b8f9ad72faa]
2021-02-17 08:31:10,929 -not-actor-/PID:73303 esrally.rally INFO OS [uname_result(system='Linux', node='draco', release='5.4.0-37-generic', version='#41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020', machine='x86_64', processor='x86_64')]
2021-02-17 08:31:10,930 -not-actor-/PID:73303 esrally.rally INFO Python [namespace(_multiarch='x86_64-linux-gnu', cache_tag='cpython-38', hexversion=50857456, name='cpython', version=sys.version_info(major=3, minor=8, micro=5, releaselevel
='final', serial=0))]
2021-02-17 08:31:10,930 -not-actor-/PID:73303 esrally.rally INFO Rally version [2.0.4]
2021-02-17 08:31:10,930 -not-actor-/PID:73303 esrally.utils.net INFO Connecting directly to the Internet (no proxy support).
2021-02-17 08:31:11,168 -not-actor-/PID:73303 esrally.rally INFO Detected a working Internet connection.
2021-02-17 08:31:11,168 -not-actor-/PID:73303 esrally.rally INFO Killing running Rally processes
2021-02-17 08:31:11,235 -not-actor-/PID:73303 esrally.rally INFO Actor system already running locally? [False]
2021-02-17 08:31:11,235 -not-actor-/PID:73303 esrally.actor INFO Starting actor system with system base [multiprocTCPBase] and capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900'}].
2021-02-17 08:31:11,266 -not-actor-/PID:73315 root INFO ++++ Actor System gen (3, 10) started, admin @ ActorAddr-(T|:1900)
2021-02-17 08:31:11,279 -not-actor-/PID:73303 esrally.racecontrol INFO User specified pipeline [benchmark-only].
2021-02-17 08:31:11,279 -not-actor-/PID:73303 esrally.racecontrol INFO Using configured hosts [{'host': 'localhost', 'port': 9200}]
2021-02-17 08:31:11,280 -not-actor-/PID:73303 esrally.actor INFO Joining already running actor system with system base [multiprocTCPBase].
2021-02-17 08:31:11,282 ActorAddr-(T|:1900)/PID:73315 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSy
stem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 8, 5, 'final', 0), 'Thespian Generation': (3, 10), 'Thespian Version': '1613550671258'}] match requirements [{'coordinator': True}].
2021-02-17 08:31:11,401 -not-actor-/PID:73317 elasticsearch WARNING GET https://localhost:9200/_cluster/health?wait_for_nodes=%3E%3D1 [status:N/A request:0.095s]
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/urllib3/connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "/home/arthur/.virtualenvs/esrally/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

```

**Comment by ebadyano** [comment]
@arthurlogilab I'm not able to reproduce the issue.

Could you please post full log, once rally stops. That would show if rally client is using `verify_certs:false`. If I run without `verify_certs:false`. I get something like this, and the trace I get is similar. Although I don't get that error when running with `verify_certs:false`.
```
2021-02-20 00:28:29,569 ActorAddr-(T|:32875)/PID:1718 esrally.client INFO Creating ES client connected to [{'host': 'localhost', 'port': 39200}] with options [{'use_ssl': True, 'basic_auth_user': 'rally', 'basic_auth_password': '*****'}]
2021-02-20 00:28:29,569 ActorAddr-(T|:32875)/PID:1718 esrally.client INFO SSL support: on
2021-02-20 00:28:29,575 ActorAddr-(T|:32875)/PID:1718 esrally.client INFO SSL certificate verification: on
2021-02-20 00:28:29,575 ActorAddr-(T|:32875)/PID:1718 esrally.client INFO SSL client authentication: off
2021-02-20 00:28:29,575 ActorAddr-(T|:32875)/PID:1718 esrally.client INFO HTTP basic authentication: on
2021-02-20 00:28:29,575 ActorAddr-(T|:32875)/PID:1718 esrally.client INFO HTTP compression: off
2021-02-20 00:30:30,789 ActorAddr-(T|:32875)/PID:1718 esrally.actor ERROR Error in race control
Traceback (most recent call last):
```

**Comment by danielmitterdorfer** [comment]
No further feedback received. @arthurlogilab if you have the requested information please add it in a comment and we can look at re-opening this issue.
