### ISSUE TITLE
Track code imports can fail due to deferred dependency install

### ISSUE THREAD

**Issue by DJRickyB** [elastic/rally#1474]
If an import is not bounded by a try/catch or nested in an invoked function, and the dependency requires #1405, it can fail with an ImportError.
```
[ERROR] Cannot race. Traceback (most recent call last):
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/utils/modules.py", line 106, in load
    root_module = self._load_component(component_name, module_dirs)
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/utils/modules.py", line 65, in _load_component
    m = importlib.import_module(p)
  File "/Users/rick.boyd/.pyenv/versions/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rick.boyd/.rally/benchmarks/tracks/cavokz/solutions/security/track.py", line 30, in <module>
    from security.parameter_sources.events_emitter import EventsEmitterParamSource
  File "/Users/rick.boyd/.rally/benchmarks/tracks/cavokz/solutions/security/parameter_sources/events_emitter.py", line 22, in <module>
    import geneve
ModuleNotFoundError: No module named 'geneve'
```

Likewise, but more flaky, I've seen `used_corpora` call invoke the param source function where we use a dependency but fail to resolve it in the PYTHONPATH in time, via the following stack:
```
esrally.exceptions.RallyError: Traceback (most recent call last):
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/actor.py", line 92, in guard
    return f(self, msg, sender)
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/driver/driver.py", line 535, in receiveMsg_WorkerIdle
    self.transition_when_all_children_responded(sender, msg, self.Status.PROCESSOR_RUNNING, self.Status.PROCESSOR_COMPLETE, self.resume)
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/actor.py", line 157, in transition_when_all_children_responded
    transition()
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/driver/driver.py", line 510, in resume
    self._seed_tasks(self.processors.get())
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/driver/driver.py", line 518, in _seed_tasks
    self.tasks = list(WorkerTask(func, params) for func, params in processor.on_prepare_track(self.track, self.data_root_dir))
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/driver/driver.py", line 518, in <genexpr>
    self.tasks = list(WorkerTask(func, params) for func, params in processor.on_prepare_track(self.track, self.data_root_dir))
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/track/loader.py", line 467, in on_prepare_track
    for corpus in used_corpora(track):
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/track/loader.py", line 434, in used_corpora
    param_source = operation_parameters(t, sub_task)
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/track/loader.py", line 423, in operation_parameters
    return params.param_source_for_name(op.param_source, t, op.params)
  File "/Users/rick.boyd/scratch/test_geneve/.venv/lib/python3.9/site-packages/esrally/track/params.py", line 51, in param_source_for_name
    return param_source(track, params)
  File "/Users/rick.boyd/.rally/benchmarks/tracks/cavokz/solutions/security/parameter_sources/events_emitter.py", line 84, in __init__
    schema = kwargs["_test_schema"] if "_test_schema" in kwargs else load_schema(track, params)
  File "/Users/rick.boyd/.rally/benchmarks/tracks/cavokz/solutions/security/parameter_sources/events_emitter.py", line 44, in load_schema
    return geneve.utils.load_schema(params["schema"]["uri"], params["schema"]["path"], track.root)
NameError: name 'geneve' is not defined
```

The second error seems to only happen the first time a track is run. We should (a) ensure dependency installation happens as early as possible and (b) (stretch goal) get `param_source.__init__()` out of the path of execution for the track preparator, if possible.

I will attach a simple reproduction soon

**Comment by pquentin** [comment]
I will be interested to see the reproduction to better understand what is going on! I have two questions already:

* Was `geneve` installed in both cases?
* What does it mean to "fail to resolve in the classpath in time"? Did you mean PYTHONPATH?

**Comment by DJRickyB** [comment]
> Was geneve installed in both cases?

In both cases, it was not. Had to guard-rail the import with a try-catch in order to get it to ignore the importerror long enough to get the dependency installed and the track running. This was not functionally broken but the workaround is ugly.


> Did you mean PYTHONPATH?

Yes. I've given the description a couple of updates, including the intention of the issue. Track code is touched many times during race initialization, using importlib and in order to quantify which corpora we're dealing with. Those things need to be better accounted for or dealt with in the `dependencies` machinery, if it's going to stay.
