### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by Destroyer** [elastic/rally#1477]
**Rally version** (get with `esrally --version`):
fails
pip installing https://files.pythonhosted.org/packages/eb/ca/371dcc49c7abcdb1bc8fec8aa76467658c891d935f0c2967137ff036a324/esrally-1.4.1-py3-none-any.whl

**Invoked command**:
esrally --version

**Configuration file (located in `~/.rally/rally.ini`))**:
\-

**OS version**:
Debian 10

**Description of the problem including expected versus actual behavior**:
Seems like markupsafe removed the function and pip requirements dont disallow installing the new version of MarkupSafe

Collecting MarkupSafe>=0.23 (from Jinja2==2.10.3->esrally)
  Downloading https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz 

**Steps to reproduce**:
 1. pip3 install esrally
 2. esrally --version
 3. fail

**Provide logs (if relevant)**:
```
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 6, in <module>
    from esrally.rally import main
  File "/usr/local/lib/python3.7/dist-packages/esrally/rally.py", line 28, in <module>
    from esrally import version, actor, config, paths, racecontrol, reporter, metrics, track, chart_generator, exceptions, \
  File "/usr/local/lib/python3.7/dist-packages/esrally/racecontrol.py", line 26, in <module>
    from esrally import actor, config, doc_link, driver, exceptions, mechanic, metrics, reporter, track, PROGRAM_NAME
  File "/usr/local/lib/python3.7/dist-packages/esrally/driver/__init__.py", line 19, in <module>
    from .driver import DriverActor, PrepareBenchmark, PreparationComplete, StartBenchmark, BenchmarkComplete, TaskFinished
  File "/usr/local/lib/python3.7/dist-packages/esrally/driver/driver.py", line 27, in <module>
    from esrally import actor, config, exceptions, metrics, track, client, paths, PROGRAM_NAME, telemetry
  File "/usr/local/lib/python3.7/dist-packages/esrally/track/__init__.py", line 18, in <module>
    from .loader import (
  File "/usr/local/lib/python3.7/dist-packages/esrally/track/loader.py", line 26, in <module>
    import jinja2
  File "/usr/local/lib/python3.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python3.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python3.7/dist-packages/jinja2/utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/dist-packages/markupsafe/__init__.py)
```

Fix
pip3 uninstall MarkupSafe
pip3 install MarkupSafe==1.1.1

**Comment by DJRickyB** [comment]
Hi! I have not confirmed that this is the problem, but I see you are using python 3.7. Currently Rally only supports 3.8, 3.9, and 3.10. Can you still reproduce if you upgrade your Python version?

**Comment by Destroyer** [comment]
Ooops, didn't expect Python on a supported Debian version would be already unsupported, 3.8 works

**Comment by pquentin** [comment]
Right, we dropped Python 3.7 because we needed certain Python 3.8 features (https://github.com/elastic/rally/pull/934), sorry that you ran onto this. I'm not currently anticipating dropping Python 3.8 earlier than its official EOL though.
