### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/xxx'

### ISSUE THREAD

**Issue by UchihaYuki** [elastic/rally#1483]
**Rally version** (get with `esrally --version`):  the one ship with docker

**Invoked command**:
```yaml
version: '3.4'

services:
  rally:
    image: elastic/rally:2.3.1
    command: 
      - race
      - --track=geonames
      - --test-mode
      - --pipeline=benchmark-only
      - --target-hosts=es-1.${BASE_DOMAIN}:16661,es-2.${BASE_DOMAIN}:16662,es-3.${BASE_DOMAIN}:16663
      - --challenge=append-no-conflicts
      - --car=8gheap
      - --client-options=use_ssl:true,verify_certs:false,basic_auth_user:'elastic',basic_auth_password:'${ADMIN_PASSWORD}'    
    volumes:
      - /home/yuki/rally/rally/rally.ini:/rally/.rally/rally.ini
```

**Configuration file (located in `~/.rally/rally.ini`))**: the one ship with docker

**JVM version**: the one ship with docker

**OS version**: the one ship with docker

**Description of the problem including expected versus actual behavior**:
After `docker-compose up` I got:
```
[INFO] Race id is [47acbf53-f23f-415c-9461-74e093338094]
[ERROR] Cannot race. Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/esrally/actor.py", line 92, in guard
    return f(self, msg, sender)
  File "/usr/local/lib/python3.8/site-packages/esrally/racecontrol.py", line 110, in receiveMsg_Setup
    self.coordinator.setup(sources=msg.sources)
  File "/usr/local/lib/python3.8/site-packages/esrally/racecontrol.py", line 194, in setup
    self.current_track = track.load_track(self.cfg)
  File "/usr/local/lib/python3.8/site-packages/esrally/track/loader.py", line 191, in load_track
    repo = track_repo(cfg)
  File "/usr/local/lib/python3.8/site-packages/esrally/track/loader.py", line 284, in track_repo
    return GitTrackRepository(cfg, fetch, update)
  File "/usr/local/lib/python3.8/site-packages/esrally/track/loader.py", line 320, in __init__
    self.repo = repo_class(remote_url, tracks_dir, repo_name, "tracks", offline, fetch)
  File "/usr/local/lib/python3.8/site-packages/esrally/utils/repo.py", line 43, in __init__
    git.clone(src=self.repo_dir, remote=self.url)
  File "/usr/local/lib/python3.8/site-packages/esrally/utils/git.py", line 52, in clone
    io.ensure_dir(src)
  File "/usr/local/lib/python3.8/site-packages/esrally/utils/io.py", line 231, in ensure_dir
    os.makedirs(directory, mode, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yuki'


Getting further help:
*********************
* Check the log files in /rally/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/2.3.1/.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /rally/.rally/logs.

-------------------------------
[INFO] FAILURE (took 4 seconds)
-------------------------------
```

**Steps to reproduce**:
just run the docker-compose.yml provided above, my user id (yuki) is 1000, and I'll get this error, when I provide custom rally.ini. If I don't provide custom rally.ini with volume mount, everything is fine.
Here is the doc I reference:
https://esrally.readthedocs.io/en/stable/docker.html

**Provide logs (if relevant)**:

**Comment by UchihaYuki** [comment]
Sorry for the noise. I made some mistake in rally.ini which points to my host path.
