### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Sumit-Tafe** [elastic/rally#1509]
**Rally version** (get with `esrally --version`):
esrally.exe 2.4.0
**Invoked command**:
C:\Program Files\Python310>esrally race --distribution-version=6.8.0 --track=geonames
**Configuration file (located in `~/.rally/rally.ini`))**:
C:\Users\sarora19\.rally
**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:
Tried to run below commands:
C:\Program Files\Python310>esrally race --distribution-version=6.8.0 --track=geonames

Error as below:
[ERROR] Cannot race. [WinError 193] %1 is not a valid Win32 application
        Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\mechanic.py", line 590, in receiveMsg_StartNodes
    self.mechanic.start_engine()
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\mechanic.py", line 707, in start_engine
    self.nodes = self.launcher.start(self.node_configs)
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\launcher.py", line 133, in start
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\launcher.py", line 133, in <listcomp>
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\launcher.py", line 163, in _start_node
    node_pid = self._start_process(binary_path, env)
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\launcher.py", line 217, in _start_process
    ret = ProcessLauncher._run_subprocess(command_line=" ".join(cmd), env=env)
  File "C:\Program Files\Python310\lib\site-packages\esrally\mechanic\launcher.py", line 203, in _run_subprocess
    with subprocess.Popen(
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

Getting further help:
*********************
* Check the log files in C:\Users\sarora19\.rally\logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/2.4.0/.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in C:\Users\sarora19\.rally\logs.

--------------------------------
[INFO] FAILURE (took 34 seconds)
--------------------------------

**Provide logs (if relevant)**:

refer the attached file

[rally.log](https://github.com/elastic/rally/files/8820883/rally.log)

**Comment by pquentin** [comment]
Hello, thank you for your interest in Rally.

Unfortunaty, Rally is developed for Unix and is actively tested on Linux and macOS. Rally supports [benchmarking Elasticsearch clusters running on Windows](http://esrally.readthedocs.io/en/stable/recipes.html#benchmarking-an-existing-cluster) but Rally itself needs to be installed on machines running Unix.
