### ISSUE TITLE
esrally.exceptions.InvalidSyntax: 'index' or 'data-stream' is mandatory and is missing for operation 'search'

### ISSUE THREAD

**Issue by purple910** [elastic/rally#1585]
**track.json**：
```
{% import "rally.helpers" as rally with context %}
{
  "version": 2,
  "description": "Tracker-generated track for cme",
  "indices": [
    {
      "name": "pdf_v2",
      "body": "pdf_v2.json"
    }, 
    {
      "name": "zn_v2",
      "body": "zn_v2.json"
    }
  ],
  "corpora": [
    {
      "name": "pdf_v2",
      "documents": [
        {
          "target-index": "pdf_v2",
          "source-file": "pdf_v2-documents.json.bz2",
          "document-count": 36250,
          "compressed-bytes": 107243297,
          "uncompressed-bytes": 618147656
        }
      ]
    }, 
    {
      "name": "zn_v2",
      "documents": [
        {
          "target-index": "zn_v2",
          "source-file": "zn_v2-documents.json.bz2",
          "document-count": 1411125,
          "compressed-bytes": 733857315,
          "uncompressed-bytes": 4081869683
        }
      ]
    }
  ],
  "schedule": [
    {
      "operation": "delete-index"
    },
    {
      "operation": {
        "operation-type": "create-index",
        "settings": {{index_settings | default({}) | tojson}}
      }
    },
    {
      "operation": {
        "operation-type": "cluster-health",
        "index": "pdf_v2,zn_v2",
        "request-params": {
          "wait_for_status": "{{cluster_health | default('green')}}",
          "wait_for_no_relocating_shards": "true"
        },
        "retry-until-success": true
      }
    },
    {
      "operation": {
        "operation-type": "bulk",
        "bulk-size": 5000
      },
      "warmup-time-period": 120,
      "clients": 8
    },
    {
      "operation": {
        "operation-type": "force-merge"
      }
    },
    {
      "operation": {
        "operation-type": "search",
        "body": {
          "query": {
            "match_all": {}
          }
        }
      },
      "clients": 8,
      "warmup-iterations": 1000,
      "iterations": 1000,
      "target-throughput": 100
    }
  ]
}
```

**esrally version**: 2.6.0

**Invoked command**:  srally race --track-path=/root/tracks/cme/  --pipeline=benchmark-only  --target-hosts=192.168.9.239:9200 --client-options="basic_auth_user:'elastic',basic_auth_password:'EC05E3BB626EBB7FB06052614C453ACF'" 

**Configuration file:** 
[meta]
config.version = 17
[system]
env.name = local
[node]
root.dir = /root/.rally/benchmarks
src.root.dir = /root/.rally/benchmarks/src
[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch
[benchmarks]
local.dataset.cache = /root/.rally/benchmarks/data
[reporting]
datastore.type = in-memory
datastore.host =
datastore.port =
datastore.secure = False
datastore.user =
datastore.password =
[tracks]
default.url = https://github.com/elastic/rally-tracks
[teams]
default.url = https://github.com/elastic/rally-teams
[defaults]
preserve_benchmark_candidate = false
[distributions]
release.cache = true

**JVM版本**: 1.8.0_331

**OS version:** 
```
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Steps to reproduce**
> esrally create-track --track=cme --target-hosts=192.168.9.239:9200 --client-options="basic_auth_user:'elastic',basic_auth_password:'EC05E3BB626EBB7FB06052614C453ACF'" --indices="pdf_v2,zn_v2" --output-path=~/tracks
> Modify the track.json file and add force merge and search
>  srally race --track-path=/root/tracks/cme/  --pipeline=benchmark-only  --target-hosts=192.168.9.239:9200 --client-options="basic_auth_user:'elastic',basic_auth_password:'EC05E3BB626EBB7FB06052614C453ACF'" 

**ERROR logs :**
2022-09-25 04:49:39,777 ActorAddr-(T|:40853)/PID:30317 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 8, 6, 'final', 0), 'Thespian Generation': (3, 10), 'Thespian Version': '1664081379574'}] match requirements [{}].
2022-09-25 04:49:39,826 ActorAddr-(T|:45199)/PID:30316 esrally.metrics INFO Closing metrics store.
2022-09-25 04:49:39,780 ActorAddr-(T|:40853)/PID:30317 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 8, 6, 'final', 0), 'Thespian Generation': (3, 10), 'Thespian Version': '1664081379574'}] match requirements [{}].
2022-09-25 04:49:39,827 ActorAddr-(T|:37783)/PID:30314 esrally.actor INFO Received a benchmark failure from [ActorAddr-(T|:45199)] and will forward it now.
2022-09-25 04:49:39,829 -not-actor-/PID:30302 esrally.racecontrol ERROR A benchmark failure has occurred
2022-09-25 04:49:39,784 ActorAddr-(T|:40853)/PID:30317 esrally.actor INFO Transitioning from [Status.INITIALIZING] to [Status.PROCESSOR_RUNNING].
2022-09-25 04:49:39,829 -not-actor-/PID:30302 esrally.racecontrol INFO Telling benchmark actor to exit.
2022-09-25 04:49:39,807 ActorAddr-(T|:40853)/PID:30317 esrally.actor INFO Transitioning from [Status.PROCESSOR_COMPLETE] to [Status.PROCESSOR_RUNNING].
2022-09-25 04:49:39,821 ActorAddr-(T|:40853)/PID:30317 esrally.actor ERROR Error in track preparator
Traceback (most recent call last):

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/actor.py", line 92, in guard
    return f(self, msg, sender)

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 538, in receiveMsg_WorkerIdle
    self.transition_when_all_children_responded(sender, msg, self.Status.PROCESSOR_RUNNING, self.Status.PROCESSOR_COMPLETE, self.resume)

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/actor.py", line 157, in transition_when_all_children_responded
    transition()

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 513, in resume
    self._seed_tasks(self.processors.get())

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 521, in _seed_tasks
    self.tasks = list(WorkerTask(func, params) for func, params in processor.on_prepare_track(self.track, self.data_root_dir))

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 521, in <genexpr>
    self.tasks = list(WorkerTask(func, params) for func, params in processor.on_prepare_track(self.track, self.data_root_dir))

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/loader.py", line 467, in on_prepare_track
    for corpus in used_corpora(track):

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/loader.py", line 434, in used_corpora
    param_source = operation_parameters(t, sub_task)

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/loader.py", line 425, in operation_parameters
    return params.param_source_for_operation(op.type, t, op.params, task.name)

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/params.py", line 40, in param_source_for_operation
    return __PARAM_SOURCES_BY_OP[op_type](track, params, operation_name=task_name)

  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/params.py", line 523, in __init__
    raise exceptions.InvalidSyntax(

esrally.exceptions.InvalidSyntax: 'index' or 'data-stream' is mandatory and is missing for operation 'search'

2022-09-25 04:49:39,830 ActorAddr-(T|:37783)/PID:30314 esrally.actor INFO BenchmarkActor received unknown message [ActorExitRequest] (ignoring).
2022-09-25 04:49:39,831 ActorAddr-(T|:34021)/PID:30315 esrally.actor INFO MechanicActor#receiveMessage unrecognized(msg = [<class 'thespian.actors.ActorExitRequest'>] sender = [ActorAddr-(T|:37783)])
2022-09-25 04:49:39,831 ActorAddr-(T|:45199)/PID:30316 esrally.actor INFO Main driver received ActorExitRequest and will terminate all load generators.
2022-09-25 04:49:39,832 ActorAddr-(T|:40853)/PID:30317 esrally.actor INFO ActorExitRequest received. Forwarding to children
2022-09-25 04:49:39,832 ActorAddr-(T|:37783)/PID:30314 esrally.actor INFO BenchmarkActor received unknown message [ChildActorExited:ActorAddr-(T|:34021)] (ignoring).
2022-09-25 04:49:39,834 ActorAddr-(T|:37783)/PID:30314 esrally.actor INFO BenchmarkActor received unknown message [ChildActorExited:ActorAddr-(T|:34021)] (ignoring).
2022-09-25 04:49:39,842 ActorAddr-(T|:45199)/PID:30316 esrally.actor INFO A track preparator has exited.
2022-09-25 04:49:39,843 ActorAddr-(T|:37783)/PID:30314 esrally.actor INFO BenchmarkActor received unknown message [ChildActorExited:ActorAddr-(T|:45199)] (ignoring).
2022-09-25 04:49:42,832 -not-actor-/PID:30302 esrally.rally INFO Attempting to shutdown internal actor system.
2022-09-25 04:49:42,834 -not-actor-/PID:30313 root INFO ActorSystem Logging Shutdown
2022-09-25 04:49:42,855 -not-actor-/PID:30312 root INFO ---- Actor System shutdown
2022-09-25 04:49:42,855 -not-actor-/PID:30302 esrally.rally INFO Actor system is still running. Waiting...
2022-09-25 04:49:43,856 -not-actor-/PID:30302 esrally.rally INFO Shutdown completed.
2022-09-25 04:49:43,856 -not-actor-/PID:30302 esrally.rally ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/rally.py", line 983, in dispatch_sub_command
    race(cfg, args.kill_running_processes)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/rally.py", line 761, in race
    with_actor_system(racecontrol.run, cfg)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/rally.py", line 791, in with_actor_system
    runnable(cfg)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/racecontrol.py", line 373, in run
    raise e
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/racecontrol.py", line 370, in run
    pipeline(cfg)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/racecontrol.py", line 71, in __call__
    self.target(cfg)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/racecontrol.py", line 309, in benchmark_only
    return race(cfg, external=True)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/racecontrol.py", line 267, in race
    raise exceptions.RallyError(result.message, result.cause)
esrally.exceptions.RallyError: Traceback (most recent call last):
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/actor.py", line 92, in guard
    return f(self, msg, sender)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 538, in receiveMsg_WorkerIdle
    self.transition_when_all_children_responded(sender, msg, self.Status.PROCESSOR_RUNNING, self.Status.PROCESSOR_COMPLETE, self.resume)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/actor.py", line 157, in transition_when_all_children_responded
    transition()
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 513, in resume
    self._seed_tasks(self.processors.get())
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 521, in _seed_tasks
    self.tasks = list(WorkerTask(func, params) for func, params in processor.on_prepare_track(self.track, self.data_root_dir))
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/driver/driver.py", line 521, in <genexpr>
    self.tasks = list(WorkerTask(func, params) for func, params in processor.on_prepare_track(self.track, self.data_root_dir))
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/loader.py", line 467, in on_prepare_track
    for corpus in used_corpora(track):
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/loader.py", line 434, in used_corpora
    param_source = operation_parameters(t, sub_task)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/loader.py", line 425, in operation_parameters
    return params.param_source_for_operation(op.type, t, op.params, task.name)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/params.py", line 40, in param_source_for_operation
    return __PARAM_SOURCES_BY_OP[op_type](track, params, operation_name=task_name)
  File "/opt/tutorial-env/lib/python3.8/site-packages/esrally/track/params.py", line 523, in __init__
    raise exceptions.InvalidSyntax(
esrally.exceptions.InvalidSyntax: 'index' or 'data-stream' is mandatory and is missing for operation 'search'

**Comment by pquentin** [comment]
Hello! Thanks very much for your interest in Rally.

I'm assuming you closed this because you fixed your issue by adding an index name to the search operation.

Note that we'd like to direct user questions to the [forums](https://discuss.elastic.co/tag/rally). If you can stop by there next time, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [forums](https://discuss.elastic.co/tag/rally) that should be able to help get an answer to your questions.
