### ISSUE TITLE
Update ES Python client version to support include_empty_fields in field caps API

### ISSUE THREAD

**Issue by gbanasiak** [elastic/rally#1829]
This became visible after https://github.com/elastic/rally-tracks/pull/562.

```
2024-02-19 00:22:57,437 ActorAddr-(T|:42217)/PID:25267 esrally.driver.driver INFO Worker[0] executing tasks: ['field-caps-exclude-empty-fields', 'field-caps-exclude-empty-fields']
2024-02-19 00:22:57,441 ActorAddr-(T|:42217)/PID:25267 esrally.driver.driver ERROR Could not execute schedule
Traceback (most recent call last):
  File "/home/esbench/rally/esrally/driver/driver.py", line 1934, in __call__
    total_ops, total_ops_unit, request_meta_data = await execute_single(runner, self.es, params, self.on_error)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esbench/rally/esrally/driver/driver.py", line 2028, in execute_single
    return_value = await runner(es, params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esbench/rally/esrally/driver/runner.py", line 298, in __call__
    return await self.delegate(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esbench/rally/esrally/driver/runner.py", line 413, in __call__
    return_value = await self.delegate(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esbench/rally/esrally/driver/runner.py", line 346, in __call__
    return await self.delegate(self.client_extractor(args[0]), *args[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esbench/rally/esrally/driver/runner.py", line 2850, in __call__
    await es.field_caps(index=index, body=body, fields=fields, params=request_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esbench/.local/lib/python3.11/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncElasticsearch.field_caps() got an unexpected keyword argument 'include_empty_fields'
```

The support for `include_empty_fields` request parameter is included in current ES Python client main branch ([src](https://github.com/elastic/elasticsearch-py/blob/f0fdf218d61e4b2c5ab0aef939ca330c2a8e4241/elasticsearch/_async/client/__init__.py#L1748)), so should be released with the next version.

**Comment by pquentin** [comment]
Note that `include_empty_fields` is specified to be 8.13 only: https://github.com/elastic/elasticsearch-specification/pull/2413 was not backported. This means Rally has to wait for elasticsearch-py 8.13.0, which should be out some time next month.
