### ISSUE TITLE
Provide better feedback on authentication errors against the (ES) metrics store

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#194]
When running rally, if the metrics store is inaccessible, the error is currently not very useful:

```2016-12-12 10:01:03,902 rally.main INFO Rally version [0.4.6]
2016-12-12 10:01:03,902 rally.main INFO Command line arguments: Namespace(advanced_config=False, assume_defaults=False, car='defaults', challenge='append-no-conflicts', client_options="basic_auth_user:'es_admin',basic_auth_password:'changeme'", cluster_health='green', configuration_name=None, data_paths=None, distribution_repository='release', distribution_version='', effective_start_date=datetime.datetime(2016, 12, 12, 10, 1, 3, 895502), laps=1, logging='file', offline=False, override_src_dir=None, pipeline='benchmark-only', preserve_install='False', quiet=False, report_file='', report_format='markdown', revision='current', subcommand=None, target_hosts='localhost:9200', telemetry='', test_mode=False, track='tiny', track_repository='default', user_tag='')
2016-12-12 10:01:03,902 rally.net INFO Rally connects directly to the Internet (no proxy support).
2016-12-12 10:01:04,268 rally.main INFO Detected a working Internet connection.
2016-12-12 10:01:04,310 rally.process INFO Skipping myself (PID [66282]).
2016-12-12 10:01:14,329 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 0): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:19,331 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 0): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:24,336 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 1): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:29,339 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 1): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:29,449 rally.racecontrol INFO User specified pipeline [benchmark-only].
2016-12-12 10:01:29,450 rally.metrics INFO Creating ES metrics store
2016-12-12 10:01:29,450 rally.metrics INFO Creating connection to metrics store at localhost:9200
2016-12-12 10:01:29,451 rally.metrics INFO Opening metrics store for invocation=[20161212T100103Z], track=[tiny], challenge=[append-no-conflicts], car=[external]
2016-12-12 10:01:29,539 elasticsearch WARNING PUT /_template/rally [status:401 request:0.087s]
2016-12-12 10:01:29,539 root ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 235, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 48, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 182, in benchmark_only
    metrics_store = metrics.metrics_store(cfg, read_only=False)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 138, in metrics_store
    store.open(selected_invocation, selected_track, selected_challenge, selected_car, create=not read_only)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 553, in open
    self._client.put_template("rally", self._get_template())
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 30, in put_template
    return self.guarded(self._client.indices.put_template, name, template)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 53, in guarded
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 494, in put_template
    name), params=params, body=body)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, 'security_exception', 'unable to authenticate user [es_admin] for REST request [/_template/rally]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/esrally/rally.py", line 459, in dispatch_sub_command
    racecontrol.run(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 241, in run
    raise exceptions.RallyError("This race ended with a fatal crash.").with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 235, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 48, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 182, in benchmark_only
    metrics_store = metrics.metrics_store(cfg, read_only=False)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 138, in metrics_store
    store.open(selected_invocation, selected_track, selected_challenge, selected_car, create=not read_only)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 553, in open
    self._client.put_template("rally", self._get_template())
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 30, in put_template
    return self.guarded(self._client.indices.put_template, name, template)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 53, in guarded
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 494, in put_template
    name), params=params, body=body)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
esrally.exceptions.RallyError: This race ended with a fatal crash.
2016-12-12 10:01:29,545 rally.main INFO Attempting to shutdown internal actor system.
2016-12-12 10:01:29,625 rally.main INFO Shutdown completed.
```
In this case, I had some old/incorrect details in ```~/.rally/rally.ini``` that I had yet to update or remove.

A more informative error message might be:
```
Access to the rally metrics store 'localhost' using auth credentials for 'es_rally' 
are invalid or the endpoint is unreachable. 
Please review the metrics store details in ~/.rally/rally.ini 
or verify the endpoint is running and reachable.
```

**Comment by geekpete** [comment]
When running rally, if the metrics store is inaccessible, the error is currently not very useful:

```2016-12-12 10:01:03,902 rally.main INFO Rally version [0.4.6]
2016-12-12 10:01:03,902 rally.main INFO Command line arguments: Namespace(advanced_config=False, assume_defaults=False, car='defaults', challenge='append-no-conflicts', client_options="basic_auth_user:'es_admin',basic_auth_password:'changeme'", cluster_health='green', configuration_name=None, data_paths=None, distribution_repository='release', distribution_version='', effective_start_date=datetime.datetime(2016, 12, 12, 10, 1, 3, 895502), laps=1, logging='file', offline=False, override_src_dir=None, pipeline='benchmark-only', preserve_install='False', quiet=False, report_file='', report_format='markdown', revision='current', subcommand=None, target_hosts='localhost:9200', telemetry='', test_mode=False, track='tiny', track_repository='default', user_tag='')
2016-12-12 10:01:03,902 rally.net INFO Rally connects directly to the Internet (no proxy support).
2016-12-12 10:01:04,268 rally.main INFO Detected a working Internet connection.
2016-12-12 10:01:04,310 rally.process INFO Skipping myself (PID [66282]).
2016-12-12 10:01:14,329 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 0): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:19,331 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 0): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:24,336 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 1): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:29,339 root WARNING Unable to get address info for address Peters-MacBook-Pro-2.local (AddressFamily.AF_INET, SocketKind.SOCK_DGRAM, 17, 1): <class 'socket.gaierror'> [Errno 8] nodename nor servname provided, or not known
2016-12-12 10:01:29,449 rally.racecontrol INFO User specified pipeline [benchmark-only].
2016-12-12 10:01:29,450 rally.metrics INFO Creating ES metrics store
2016-12-12 10:01:29,450 rally.metrics INFO Creating connection to metrics store at localhost:9200
2016-12-12 10:01:29,451 rally.metrics INFO Opening metrics store for invocation=[20161212T100103Z], track=[tiny], challenge=[append-no-conflicts], car=[external]
2016-12-12 10:01:29,539 elasticsearch WARNING PUT /_template/rally [status:401 request:0.087s]
2016-12-12 10:01:29,539 root ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 235, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 48, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 182, in benchmark_only
    metrics_store = metrics.metrics_store(cfg, read_only=False)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 138, in metrics_store
    store.open(selected_invocation, selected_track, selected_challenge, selected_car, create=not read_only)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 553, in open
    self._client.put_template("rally", self._get_template())
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 30, in put_template
    return self.guarded(self._client.indices.put_template, name, template)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 53, in guarded
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 494, in put_template
    name), params=params, body=body)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, 'security_exception', 'unable to authenticate user [es_admin] for REST request [/_template/rally]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/esrally/rally.py", line 459, in dispatch_sub_command
    racecontrol.run(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 241, in run
    raise exceptions.RallyError("This race ended with a fatal crash.").with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 235, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 48, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.5/site-packages/esrally/racecontrol.py", line 182, in benchmark_only
    metrics_store = metrics.metrics_store(cfg, read_only=False)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 138, in metrics_store
    store.open(selected_invocation, selected_track, selected_challenge, selected_car, create=not read_only)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 553, in open
    self._client.put_template("rally", self._get_template())
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 30, in put_template
    return self.guarded(self._client.indices.put_template, name, template)
  File "/usr/local/lib/python3.5/site-packages/esrally/metrics.py", line 53, in guarded
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 494, in put_template
    name), params=params, body=body)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
esrally.exceptions.RallyError: This race ended with a fatal crash.
2016-12-12 10:01:29,545 rally.main INFO Attempting to shutdown internal actor system.
2016-12-12 10:01:29,625 rally.main INFO Shutdown completed.
```
In this case, I had some old/incorrect details in ```~/.rally/rally.ini``` that I had yet to update or remove.

A more informative error message might be:
```
Access to the rally metrics store 'localhost' using auth credentials for 'es_rally' 
are invalid or the endpoint is unreachable. 
Please review the metrics store details in ~/.rally/rally.ini 
or verify the endpoint is running and reachable.
```

**Comment by danielmitterdorfer** [comment]
We check three specific error conditions now and show the following error messages (concrete values are just examples):

On connection problems (e.g. wrong host configured, host down, network problems, ...):

```
Could not connect to your Elasticsearch metrics store. Please check that it is running on host [127.0.0.1] at port [9200] or fix the configuration in [/home/someuser/.rally/rally.ini].
```

On authentication problems (usually wrong credentials):

```
The configured user could not authenticate against your Elasticsearch metrics store running on host [127.0.0.1]  at port [9243] (wrong password?). Please fix the configuration in [/home/someuser/.rally/rally.ini].
```

On authorization problems (i.e. user is authenticated but it does not have proper privileges):

```
The configured user does not have enough privileges to run the operation [bulk] against your Elasticsearch metrics store running on host [127.0.0.1] at port [9243]. Please adjust your x-pack configuration or specify a user with enough privileges in the configuration in [/home/someuser/.rally/rally.ini].
```

On any other error we just show:

```
An unknown error occurred while running the operation [bulk] against your Elasticsearch metrics store on host [127.0.0.1] at port [9200].
```

More details about the specific exception that caused it, are contained in the logs.
