### ISSUE TITLE
track tiny is suddenly failing

### ISSUE THREAD

**Issue by grayaii** [elastic/rally#204]
**Rally version** (get with `esrally --version`):esrally 0.4.8 (also happens with 0.4.3)

**Invoked command**: esrally --pipeline=from-distribution --distribution-version=5.0.0 --track=tiny

**Configuration file (located in `~/.rally/rally.ini`))**:
```
[meta]
config.version = 6

[system]
root.dir = /home/ec2-user/.rally/benchmarks
log.root.dir = logs
env.name = local

[provisioning]
local.install.dir = install

[runtime]
java8.home = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b15.25.amzn1.x86_64

[benchmarks]
local.dataset.cache = ${system:root.dir}/data

[reporting]
datastore.type = in-memory
datastore.host =
datastore.port =
datastore.secure =
datastore.user =
datastore.password =

[tracks]
default.url = https://github.com/elastic/rally-tracks

[defaults]
preserve_benchmark_candidate = False
```
**JVM version**: java-1.8.0-openjdk-1.8.0.111

**OS version**: AWS EC2 Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. We have been running this command successfully for quite some time:
esrally --pipeline=from-distribution --distribution-version=5.0.0 --track=tiny

And it is now failing.

**Provide logs (if relevant)**:
```
2017-01-25 14:35:00,7 rally.track INFO Checking out [5] in [/home/ec2-user/.rally/benchmarks/tracks/default] for distribution version [5.0.0].
2017-01-25 14:35:00,24 rally.track INFO Rebasing on [5] in [/home/ec2-user/.rally/benchmarks/tracks/default] for distribution version [5.0.0].
2017-01-25 14:35:00,108 rally.track INFO Reading track specification file [/home/ec2-user/.rally/benchmarks/tracks/default/tiny/track.json].
2017-01-25 14:35:00,110 root ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 328, in read
    rendered = render_template_from_file(track_spec_file)
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 270, in render_template_from_file
    return render_template(loader=jinja2.FileSystemLoader(io.dirname(template_file_name)), template_name=io.basename(template_file_name))
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 264, in render_template
    template = env.get_template(template_name)
  File "/usr/local/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python3.4/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: track.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 234, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 48, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 175, in from_distribution
    return race(Benchmark(cfg, mechanic.create(cfg, metrics_store, distribution=True), metrics_store), cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 151, in race
    benchmark.setup()
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 62, in setup
    self.track = track.load_track(self.cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 69, in load_track
    "%s/%s" % (data_root, track_name.lower()))
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 331, in read
    except (json.JSONDecodeError, jinja2.exceptions.TemplateError) as e:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/esrally/rally.py", line 459, in dispatch_sub_command
    racecontrol.run(cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 240, in run
    raise exceptions.RallyError("This race ended with a fatal crash.").with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 234, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 48, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 175, in from_distribution
    return race(Benchmark(cfg, mechanic.create(cfg, metrics_store, distribution=True), metrics_store), cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 151, in race
    benchmark.setup()
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 62, in setup
    self.track = track.load_track(self.cfg)
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 69, in load_track
    "%s/%s" % (data_root, track_name.lower()))
  File "/usr/local/lib/python3.4/site-packages/esrally/track/loader.py", line 331, in read
    except (json.JSONDecodeError, jinja2.exceptions.TemplateError) as e:
esrally.exceptions.RallyError: This race ended with a fatal crash.
2017-01-25 14:35:00,125 rally.main INFO Attempting to shutdown internal actor system.
2017-01-25 14:35:00,182 rally.main INFO Shutdown completed.
```
Sure enough, that file does not exist:
```
[ec2-user@ip-172-31-15-245 ~]$ cat /home/ec2-user/.rally/benchmarks/tracks/default/tiny/track.json
cat: /home/ec2-user/.rally/benchmarks/tracks/default/tiny/track.json: No such file or directory
```

**Comment by grayaii** [comment]
I see that this commit broke it:
https://github.com/elastic/rally-tracks/commit/fd3891e70f9a6c148e436cb1c50764a3ccf0f4c0

**Comment by danielmitterdorfer** [comment]
Hi @grayaii! Thank you for your detailed report but I removed the tiny track intentionally. To not discover this after the fact, I suggest you have a look in our Discuss forum where I've announced the removal a while ago (see the "Breaking changes" sections):

* First announcement in the [Rally 0.4.5. release post](https://discuss.elastic.co/t/rally-0-4-5-released/66863)
* Last announcement in the [Rally 0.4.7 release post](https://discuss.elastic.co/t/rally-0-4-7-released/71060)

The release posts, and also the commit message you mentioned, document the current solution. So instead of running:

`esrally --pipeline=from-distribution --distribution-version=5.0.0 --track=tiny`

You should now run:

`esrally --pipeline=from-distribution --distribution-version=5.0.0 --track=geonames --test-mode` (actually this works with any track or challenge)

I've also documented this command line option now (see 6d633647136e2a6ceaab2ccfab0ce4aeaa49b655 and also online at http://esrally.readthedocs.io/en/latest/command_line_reference.html#test-mode)

A little trick by the way: A few months ago, I simplified the command line interface a bit and there is no need to define the pipeline in this case as Rally can automatically derive it. So this is sufficient:

`esrally --distribution-version=5.0.0 --track=geonames --test-mode`

Note that you most likely the throughput numbers may be missing. This is expected and nothing to worry about. The tiny track and also `--test-mode` are just meant for quick verification whether the setup and the track are fine. The numbers themselves are meaningless.
