### ISSUE TITLE
Cannot determine CPU info for POWER8 chips

### ISSUE THREAD

**Issue by mcgino** [elastic/rally#253]
Hi everyone.
     I have a touble about esrally.
     When I start esrally after install,system say "Exception: py-cpuinfo currently only works on X86 and some ARM CPUs."
    what can I do next?
   CPU:OPENPOWER8
   OS:REDFLAG 7

thanks.

[root@bogon rally]# esrally
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 11, in <module>
    load_entry_point('esrally==0.5.3.dev0', 'console_scripts', 'esrally')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/rally.py", line 12, in <module>
    from esrally import version, actor, config, paths, racecontrol, reporter, metrics, track, exceptions, facts
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/racecontrol.py", line 7, in <module>
    from esrally.mechanic import mechanic
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/mechanic/mechanic.py", line 8, in <module>
    from esrally.mechanic import supplier, provisioner, launcher
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/mechanic/provisioner.py", line 9, in <module>
    from esrally.mechanic import car
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/mechanic/car.py", line 4, in <module>
    from esrally.utils import sysstats, console
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/utils/sysstats.py", line 2, in <module>
    import cpuinfo
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/py_cpuinfo-0.2.3-py3.6.egg/cpuinfo/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/py_cpuinfo-0.2.3-py3.6.egg/cpuinfo/cpuinfo.py", line 1553, in <module>
  File "/usr/local/lib/python3.6/site-packages/py_cpuinfo-0.2.3-py3.6.egg/c

**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by danielmitterdorfer** [comment]
Thanks for raising this. We only tested Rally on x86 architectures so far. I see whether Rally can degrade more gracefully in this case and come back to you.

**Comment by danielmitterdorfer** [comment]
@mcgino I've pushed a fix on master. Can you please updated to the latest master version and retry? (I've seen that you already use Rally from master) Rally should pass this stage now but it is possible that there are more problems coming up (e.g. when sampling CPU usage). If that's the case, please raise a new issue. Thanks!
