### ISSUE TITLE
Problem with ES 1.2.3

### ISSUE THREAD

**Issue by pduka** [elastic/rally#289]
I ran into problem while trying to download and benchmark ES v.1.2.3. Apparently, Python script in Rally 0.6.1 is complaining about not being able to extract ES bundle for this version. Tests never start, race always fail on this step.
 
Here is the relevant part of log:

2017-06-21 12:15:45,592 rally.provisioner INFO Preparing candidate locally in [/home/elasticsearch/.rally/benchmarks/races/2017-06-21-12-15-44/jatheontest/install].
2017-06-21 12:15:45,592 rally.provisioner INFO Unzipping /home/elasticsearch/.rally/benchmarks/distributions/elasticsearch-1.2.3.tar.gz to /home/elasticsearch/.rally/benchmarks/races/2017-06-21-12-15-44/jatheontest/install
2017-06-21 12:15:45,593 rally.mechanic ERROR Cannot process message [<esrally.mechanic.mechanic.StartEngine object at 0x7f19988eb748>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/esrally/mechanic/mechanic.py", line 244, in receiveMessage
    cluster = self.mechanic.start_engine()
  File "/usr/local/lib/python3.4/dist-packages/esrally/mechanic/mechanic.py", line 345, in start_engine
    self.provisioner.prepare(binary)
  File "/usr/local/lib/python3.4/dist-packages/esrally/mechanic/provisioner.py", line 49, in prepare
    self._install_binary(binary)
  File "/usr/local/lib/python3.4/dist-packages/esrally/mechanic/provisioner.py", line 72, in _install_binary
    io.decompress(binary, self.install_dir)
  File "/usr/local/lib/python3.4/dist-packages/esrally/utils/io.py", line 172, in decompress
    _do_decompress(target_directory, tarfile.open(zip_name))
  File "/usr/lib/python3.4/tarfile.py", line 1553, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
2017-06-21 12:15:45,597 rally.racecontrol INFO Starting engine has failed. Reason [file could not be opened successfully].
2017-06-21 12:15:45,597 rally.main INFO Attempting to shutdown internal actor system.
2017-06-21 12:15:45,699 rally.main INFO Shutdown completed.
2017-06-21 12:15:45,699 root ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 429, in dispatch_sub_command
    race(cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 375, in race
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 395, in with_actor_system
    runnable(cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 375, in <lambda>
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/racecontrol.py", line 323, in run
    raise e
  File "/usr/local/lib/python3.4/dist-packages/esrally/racecontrol.py", line 320, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/racecontrol.py", line 42, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/racecontrol.py", line 262, in from_distribution
    return race(Benchmark(cfg, distribution=True))
  File "/usr/local/lib/python3.4/dist-packages/esrally/racecontrol.py", line 218, in race
    benchmark.setup()
  File "/usr/local/lib/python3.4/dist-packages/esrally/racecontrol.py", line 107, in setup
    raise exceptions.RallyError(result.message)
esrally.exceptions.RallyError: file could not be opened successfully
2017-06-21 12:15:45,706 root INFO ---- Actor System shutdown

**Comment by danielmitterdorfer** [comment]
I successfully ran `esrally --distribution-version=1.2.3` with Rally 0.6.1. just now. 

Your problem *may* be caused by a corrupt download of Elasticsearch 1.2.3. You could try to wipe ~/.rally/benchmarks/distributions` and retry again.
