### ISSUE TITLE
Cluster settings in tracks are not applied

### ISSUE THREAD

**Issue by llilyy** [elastic/rally#495]
Help me, please.

**Rally version** (get with `esrally --version`): esrally 0.10.1

**Invoked command**: 
```
export ES_JAVA_OPTS="-Djava.security.policy=file://$PATH/plugin-security.policy"; esrally --distribution-version=5.6.4 --car="defaults" --user-tag="default:geonames"
```

**Configuration file (located in `~/.rally/rally.ini`))**:
default (only use `esrally configure`)

**JVM version**: openjdk version "1.8.0_161"

**OS version**: CentOS 7.4 64Bit

**Description of the problem including expected versus actual behavior**:
When I add a `export ES_JAVA_OPTS="-Djava.security.policy=file://$PATH/plugin-security.policy";` option, the cluster settings in tracks are not applied.

**rally-tracks/geonames/challenges/default.json**
```
"cluster-settings": {
  "indices.query.bool.max_clause_count": 50000 // this setting is not applied
}
```

my `plugin-security.policy` is below
```
grant {
  permission java.util.PropertyPermission "*", "read,write";
  permission java.io.FilePermission "<<ALL FILES>>", "read,write";
};
```

**Steps to reproduce**:
1. invoked command
2. when it started `large_xxx` operation, error occured in ES

**Provide logs (if relevant)**:
```
org.elasticsearch.transport.RemoteTransportException: [rally-node-0][127.0.0.1:39300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: failed to create query:
~~very long terms query~~
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:329) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:617) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.4.jar:5.6.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
        at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:125) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:138) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
        at org.elasticsearch.index.query.TermsQueryBuilder.handleTermsQuery(TermsQueryBuilder.java:453) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.query.TermsQueryBuilder.doToQuery(TermsQueryBuilder.java:414) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:617) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.6.4.jar:5.6.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.4.jar:5.6.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
```

**Comment by dliappis** [comment]
Hello @llilyy ,

I am not sure what you are trying to achieve by specifying a different `plugin-security.policy` file, especially since you are using the default Rally car configuration and testing against a distribution.

Out of curiosity I did try your setup and command line and it went past the `large_terms` operations. I fail to see how setting `ES_JAVA_OPTS` would affect [this hard coded value](https://github.com/elastic/rally-tracks/blob/5/geonames/challenges/default.json#L6-L8) in the challenges json file for `geonames`, as it's not configurable. Indeed, I checked while the test was running that cluster setting is correct:

```
$ curl -s 'localhost:39200/_cluster/settings?include_defaults=true&pretty' | grep -B3 max_clause_count
      },
      "query" : {
        "bool" : {
          "max_clause_count" : "50000"
```

**Comment by llilyy** [comment]
Hi, @dliappis. thanks your apply. 

I added `plugin-security.policy` for testing my plugin. First, I thought I had an error by using my custom plugin. So I removed plugin option `--elasticsearch-plugins=my-plugin`. However the same error occurred.
The real command that I want to run is below
```
export ES_JAVA_OPTS="-Djava.security.policy=file:///home1/irteam/plugin-security.policy"; esrally --distribution-version=5.6.4 --user-tag="plugin:geonames" --car="defaults" --elasticsearch-plugins=my-plugin
```
I checked cluster setting and got same result to you. But why ES has an error `maxClauseCount is set to 1024` when I added `ES_JAVA_OPTS`? I cannot understand.

**Comment by dliappis** [comment]
Hey @llilyy ,

At this point this doesn't look like a bug and we reserved GitHub issues for bug reports and feature requests only. Do you mind moving the discussion to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally) instead?

Thank you.
