### ISSUE TITLE
es download url below 6.3.0 version is not correct

### ISSUE THREAD

**Issue by niyanchun** [elastic/rally#573]
- rally version: 1.0.1

when rally download es, it's url is "http://xxxx/elasticsearch-oss-6.2.2.tar.gz", but correct url should be "http://xxxx/elasticsearch-6.2.2.tar.gz".  The former url is not applied to versions below 6.3.0.

**Comment by danielmitterdorfer** [comment]
Thanks for your report. However, I could not reproduce what you are describing. Can you please try the following?

```
# clear any local state
rm ~/.rally/benchmarks/distributions/elasticsearch-6.2.2.tar.gz
mv ~/.rally/logs/rally.log ~/.rally/logs/rally.log.bak
esrally --test-mode --distribution-version=6.2.2
```

If this fails with an error, then please send the log file `~/.rally/logs/rally.log` which should help us to analyze what's going on on your machine.

**Comment by dliappis** [comment]
Also confirming that on a fresh Vagrant Ubuntu box things are working as expected and the correct Elasticsearch version gets downloaded:

```
vagrant init elastic/ubuntu-16.04-x86_64
vagrant up
vagrant ssh -c 'sudo apt-get update && sudo apt-get -y install python3-pip && pip3 install esrally && esrally --test-mode --distribution-version=6.2.2'
```

**Comment by niyanchun** [comment]
@danielmitterdorfer  Sorry for the incomplete description.

The complete situation is(https://esrally.readthedocs.io/en/stable/recipes.html): I have two machines, one is coordinator(10.8.18.13), the other is candidate(10.8.18.45).  Then I executed below commands:
 
```
esrallyd start --node-ip=10.8.18.13 --coordinator-ip=10.8.18.13   # on coordinator

esrallyd start --node-ip=10.8.18.45 --coordinator-ip=10.8.18.13   # on candidate
```

Then start esrally on coordinator:

```
esrally --track=pmc --distribution-version=6.2.2 --target-hosts=10.8.18.45:9200 --offline --report-file=~/report4.md --report-format=csv --user-tag="0917:report4"
```

Error occured:

```
[allan@108413 ~]$ esrally --track=pmc --distribution-version=6.2.2 --target-hosts=10.8.18.45:9200 --offline --report-file=~/report8.md --report-format=csv --user-tag="0918:report8"

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[ERROR] Cannot race. ('Cannot download Elasticsearch distribution from [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.2.2.tar.gz]. Please check that the specified version [6.2.2] is correct.', None)
	Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 303, in fetch
    net.download(download_url, distribution_path, progress_indicator=progress)
  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/utils/net.py", line 61, in download
    raise urllib.error.HTTPError(url, r.status, "", None, None)
urllib.error.HTTPError: HTTP Error 404:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 546, in receiveMsg_StartNodes
    nodes = self.mechanic.start_engine()
  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 678, in start_engine
    binaries = self.supply()
  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 167, in __call__
    supplier.fetch()
  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 309, in fetch
    "version [%s] is correct." % (download_url, self.version))
esrally.exceptions.SystemSetupError: ('Cannot download Elasticsearch distribution from [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.2.2.tar.gz]. Please check that the specified version [6.2.2] is correct.', None)


Getting further help:
*********************
* Check the log files in /allan/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/1.0.0/
* Ask a question on the forum at https://discuss.elastic.co/c/elasticsearch/rally
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /allan/.rally/logs.

-------------------------------
[INFO] FAILURE (took 7 seconds)
-------------------------------
```

After that, I tried to download elasticsearch 6.2.2  from official, and found the url is "http://xxxx/elasticsearch-6.2.2.tar.gz" instead of "http://xxxx/elasticsearch-oss-6.2.2.tar.gz".

Then I edit the `/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py` (about line 302)，and hard code the url, it works.

```
                progress = net.Progress("[INFO] Downloading Elasticsearch %s" % self.version)
                download_url='https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.2.tar.gz'    # hardcode
                net.download(download_url, distribution_path, progress_indicator=progress)
```

**Comment by danielmitterdorfer** [comment]
Can you please also share `~/.rally/logs/rally.log` from the machine `10.8.18.45`?

Also, can you please run `git -C ~/.rally/benchmarks/teams/default branch -l` and paste the output here? I suspect that this git repository on that machine is outdated and does not contain the branch `6.2` which should actually specify the correct download URL.

**Comment by niyanchun** [comment]
OK.  `~/.rally/logs/rally.log` log from `10.8.18.45`:

```
...
2018-09-18 03:11:41,750 ActorAddr-(T|:42865)/PID:3043 esrally.metrics INFO Closing metrics store.
2018-09-18 09:24:07,776 -not-actor-/PID:3425 esrally.actor INFO Joining already running actor system with system base [multiprocTCPBase].
2018-09-18 09:24:08,71 -not-actor-/PID:2945 root INFO ActorSystem Logging Shutdown
2018-09-18 09:24:08,71 -not-actor-/PID:2944 root INFO ---- Actor System shutdown
2018-09-18 09:24:50,872 -not-actor-/PID:3457 esrally.actor INFO Starting actor system with system base [multiprocTCPBase] and capabilities [{'coordinator': False, 'ip': '10.8.18.45', 'Convention Address.IPv4': '10.8.18.13:1900'}].
2018-09-18 09:24:50,942 -not-actor-/PID:3462 root INFO ++++ Actor System gen (3, 9) started, admin @ ActorAddr-(T|:1900)
2018-09-18 09:25:51,418 ActorAddr-(T|:1900)/PID:3462 esrally.actor INFO Capabilities [{'coordinator': False, 'ip': '10.8.18.45', 'Convention Address.IPv4': '10.8.18.13:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 4, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1537262690885'}] match requirements [{'ip': '10.8.18.45'}].
2018-09-18 09:25:51,420 ActorAddr-(T|:1900)/PID:3462 esrally.actor INFO Capabilities [{'coordinator': False, 'ip': '10.8.18.45', 'Convention Address.IPv4': '10.8.18.13:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 4, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1537262690885'}] match requirements [{'ip': '10.8.18.45'}].
2018-09-18 09:25:51,434 ActorAddr-(T|:60318)/PID:3584 esrally.actor INFO Starting node(s) [0] on [10.8.18.45].
2018-09-18 09:25:51,437 ActorAddr-(T|:60318)/PID:3584 esrally.metrics INFO Opening metrics store for trial timestamp=[20180918T092550Z], track=[pmc], challenge=[append-no-conflicts], car=[['defaults']]
2018-09-18 09:25:51,552 ActorAddr-(T|:60318)/PID:3584 esrally.mechanic.supplier INFO Resolved download URL [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.2.2.tar.gz] for version [6.2.2]
2018-09-18 09:25:51,553 ActorAddr-(T|:60318)/PID:3584 esrally.mechanic.supplier INFO Starting download of Elasticsearch [6.2.2]
2018-09-18 09:25:51,554 ActorAddr-(T|:60318)/PID:3584 esrally.utils.net INFO Rally connects directly to the Internet (no proxy support).
2018-09-18 09:25:58,80 ActorAddr-(T|:60318)/PID:3584 esrally.mechanic.supplier ERROR Cannot download Elasticsearch distribution for version [6.2.2] from [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.2.2.tar.gz].
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 303, in fetch
    net.download(download_url, distribution_path, progress_indicator=progress)

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/utils/net.py", line 61, in download
    raise urllib.error.HTTPError(url, r.status, "", None, None)

urllib.error.HTTPError: HTTP Error 404:

2018-09-18 09:25:58,81 ActorAddr-(T|:60318)/PID:3584 esrally.actor ERROR Cannot process message [<esrally.mechanic.mechanic.StartNodes object at 0x7f370bd464e0>]
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 303, in fetch
    net.download(download_url, distribution_path, progress_indicator=progress)

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/utils/net.py", line 61, in download
    raise urllib.error.HTTPError(url, r.status, "", None, None)

urllib.error.HTTPError: HTTP Error 404:


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 546, in receiveMsg_StartNodes
    nodes = self.mechanic.start_engine()

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 678, in start_engine
    binaries = self.supply()

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 167, in __call__
    supplier.fetch()

  File "/opt/anaconda3/lib/python3.6/site-packages/esrally/mechanic/supplier.py", line 309, in fetch
    "version [%s] is correct." % (download_url, self.version))

esrally.exceptions.SystemSetupError: ('Cannot download Elasticsearch distribution from [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.2.2.tar.gz]. Please check that the specified version [6.2.2] is correct.', None)
```

And `git -C ~/.rally/benchmarks/teams/default branch -l` on the machine `10.8.18.45`:

```
[allan@108445 .rally]$ git -C ~/.rally/benchmarks/teams/default branch -l
* 6
  master
```

**Comment by danielmitterdorfer** [comment]
```
[allan@108445 .rally]$ git -C ~/.rally/benchmarks/teams/default branch -l
* 6
  master
```

That explains a lot. On your machine most of the branches are missing and the reason is probably because you use `--offline` in your benchmarks. In that case Rally will not check the remote repository on Github for updates and only use the locally available branches. Can you please rerun your benchmark without the `--offline` flag?

**Comment by danielmitterdorfer** [comment]
Great. I'm keeping this ticket open because I think this is actually a bug in Rally. If the remote branch is already available locally we should be able to detect that even if you use `--offline`.
