### ISSUE TITLE
i use rally test elasticsearch 5.5.3 happen error 

### ISSUE THREAD

**Issue by brookliu123** [elastic/rally#602]
2018-11-22 06:05:21,361 -not-actor-/PID:6046 root INFO ---- Actor System shutdown
2018-11-22 06:05:21,361 -not-actor-/PID:6040 esrally.rally INFO Actor system is still running. Waiting...
2018-11-22 06:05:22,362 -not-actor-/PID:6040 esrally.rally INFO Shutdown completed.
2018-11-22 06:05:22,362 -not-actor-/PID:6040 esrally.rally ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/rally.py", line 454, in dispatch_sub_command
    race(cfg)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/rally.py", line 383, in race
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/rally.py", line 404, in with_actor_system
    runnable(cfg)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/rally.py", line 383, in <lambda>
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/racecontrol.py", line 390, in run
    raise e
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/racecontrol.py", line 387, in run
    pipeline(cfg)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/racecontrol.py", line 61, in __call__
    self.target(cfg)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/racecontrol.py", line 334, in benchmark_only
    return race(cfg, external=True)
  File "/usr/local/python34/lib/python3.4/site-packages/esrally/racecontrol.py", line 286, in race
    raise exceptions.RallyError(result.message, result.cause)
esrally.exceptions.RallyError: ('Load generator [0] has exited prematurely.', None)

**Comment by brookliu123** [comment]
Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running check-cluster-health                                                   [100% done]
Running index-append                                                           [100% done]
Running refresh-after-index                                                    [100% done]
Running force-merge                                                            [100% done]
Running refresh-after-force-merge                                              [100% done]
Running index-stats                                                            [100% done]
Running node-stats                                                             [100% done]
Running default                                                                [100% done]
Running term                                                                   [100% done]
Running phrase                                                                 [100% done]
Running country_agg_uncached                                                   [100% done]
Running country_agg_cached                                                     [100% done]
Running scroll                                                                 [100% done]
Running expression                                                             [100% done]
Running painless_static                                                        [100% done]
Running painless_dynamic                                                       [100% done]
Running large_terms                                                            [ 38% done][ERROR] Cannot race. Load generator [0] has exited prematurely.

**Comment by dliappis** [comment]
Hi @brookliu123 , sorry but Github is reserved for reporting issues only. Can you please ask your question instead in the user forum at https://discuss.elastic.co/c/elasticsearch/rally?
