### ISSUE TITLE
Inconsistent timeout option documentation for external ES cluster.

### ISSUE THREAD

**Issue by VladMasarik** [elastic/rally#680]
**Rally version** (get with `esrally --version`): 
`1.0.4`

**Invoked command**:
```
esrally \
--track-path=$HOME/copy/multiple \
--target-hosts=elasticsearch \
--on-error=abort \
--pipeline=benchmark-only \
--client-options="use_ssl:true,verify_certs:false,ca_certs:'$HOME/secret/admin-ca',client_cert:'$HOME/secret/admin-cert',client_key:'$HOME/secret/admin-key'"
```

**Configuration file (located in `~/.rally/rally.ini`))**:
```
[meta]
config.version = 17

[system]
env.name = local

[node]
root.dir = /home/rally/.rally/benchmarks
src.root.dir = /home/rally/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /home/rally/.rally/benchmarks/data

[reporting]
datastore.type = in-memory
datastore.host = 
datastore.port = 
datastore.secure = 
datastore.user = 
datastore.password = 

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true
```

**JVM version**:
```
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**OS version**:
`CentOS Linux 7 (Core)`

**Description of the problem including expected versus actual behavior**:
According to the [documentation](https://esrally.readthedocs.io/en/stable/command_line_reference.html#id2) and [code](https://github.com/elastic/rally/blob/977c0de81ed47238089a1d7169bbbdf13a47e483/esrally/utils/opts.py#L134) running Rally against external cluster should have default timeout of 60 seconds.

However, [this](https://github.com/elastic/rally/blob/master/esrally/rally.py#L628) info/debug line says otherwise, and it also seems that this exception[1] confirms it.

Solution for me was adding `timeout:60` into the `--client-options` arg.

**Steps to reproduce**:
Run Rally against external Elasticsearch cluster without specifying timeout in `--client-options` but specify `--on-error=abort` arg. Somehow force Elasticsearch to respond after 10+ seconds.

**Provide logs (if relevant)**:
[1]
```
2019-04-15 08:18:53,219 -not-actor-/PID:25 elasticsearch WARNING POST https://elasticsearch:9200/_bulk [status:N/A request:10.010s]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.4/http/client.py", line 1227, in getresponse
    response.begin()
  File "/usr/lib64/python3.4/http/client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.4/http/client.py", line 348, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.4/socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.4/ssl.py", line 754, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.4/ssl.py", line 626, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 166, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.4/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.4/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10)
2019-04-15 08:18:53,223 ActorAddr-(T|:41912)/PID:25 esrally.driver.driver ERROR Could not execute schedule
Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/esrally/driver/driver.py", line 1013, in __call__
    total_ops, total_ops_unit, request_meta_data = execute_single(runner, self.es, params, self.abort_on_error)

  File "/usr/lib/python3.4/site-packages/esrally/driver/driver.py", line 1083, in execute_single
    raise exceptions.RallyAssertionError(msg)

esrally.exceptions.RallyAssertionError: ("Request returned an error. Error type: transport, Description: HTTPSConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10) (HTTPSConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10))", None)

2019-04-15 08:18:58,184 ActorAddr-(T|:41912)/PID:25 esrally.actor INFO LoadGenerator[0] has detected a benchmark failure. Notifying master...
2019-04-15 08:18:58,186 ActorAddr-(T|:45476)/PID:23 esrally.actor ERROR Main driver received a fatal exception from a load generator. Shutting down.
2019-04-15 08:18:58,187 ActorAddr-(T|:45476)/PID:23 esrally.metrics INFO Closing metrics store.
2019-04-15 08:18:58,189 ActorAddr-(T|:42098)/PID:20 esrally.actor INFO Received a benchmark failure from [ActorAddr-(T|:45476)] and will forward it now.
2019-04-15 08:18:58,192 -not-actor-/PID:12 esrally.racecontrol ERROR A benchmark failure has occurred
2019-04-15 08:18:58,193 -not-actor-/PID:12 esrally.racecontrol INFO Telling benchmark actor to exit.
2019-04-15 08:18:58,194 ActorAddr-(T|:42098)/PID:20 esrally.actor INFO BenchmarkActor received unknown message [ActorExitRequest] (ignoring).
2019-04-15 08:18:58,203 -not-actor-/PID:12 esrally.rally INFO Attempting to shutdown internal actor system.
2019-04-15 08:18:58,200 ActorAddr-(T|:42629)/PID:22 esrally.actor INFO Stopping nodes [elasticsearch-cdm-691f2w67-1] (due to ActorExitRequest)
2019-04-15 08:18:58,196 ActorAddr-(T|:45476)/PID:23 esrally.actor INFO Main driver received ActorExitRequest and will terminate all load generators.
2019-04-15 08:18:58,198 ActorAddr-(T|:41912)/PID:25 esrally.actor INFO LoadGenerator[0] is exiting due to ActorExitRequest.
2019-04-15 08:18:58,197 ActorAddr-(T|:34651)/PID:21 esrally.actor INFO MechanicActor#receiveMessage unrecognized(msg = [<class 'thespian.actors.ActorExitRequest'>] sender = [ActorAddr-(T|:42098)])
2019-04-15 08:18:58,206 ActorAddr-(T|:45476)/PID:23 esrally.actor INFO Load generator [0] has exited.
2019-04-15 08:18:58,206 ActorAddr-(T|:34651)/PID:21 esrally.actor ERROR Child actor exited with [ChildActorExited:ActorAddr-(T|:42629)] while in status [benchmark_started].
2019-04-15 08:18:58,217 ActorAddr-(T|:42098)/PID:20 esrally.actor INFO BenchmarkActor received unknown message [ChildActorExited:ActorAddr-(T|:45476)] (ignoring).
2019-04-15 08:18:58,218 ActorAddr-(T|:42098)/PID:20 esrally.actor INFO BenchmarkActor received unknown message [ActorExitRequest] (ignoring).
2019-04-15 08:18:58,228 -not-actor-/PID:19 root INFO ActorSystem Logging Shutdown
2019-04-15 08:18:58,231 -not-actor-/PID:18 root INFO ---- Actor System shutdown
2019-04-15 08:18:58,232 -not-actor-/PID:12 esrally.rally INFO Actor system is still running. Waiting...
2019-04-15 08:18:59,234 -not-actor-/PID:12 esrally.rally INFO Shutdown completed.
2019-04-15 08:18:59,234 -not-actor-/PID:12 esrally.rally ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/esrally/rally.py", line 475, in dispatch_sub_command
    race(cfg)
  File "/usr/lib/python3.4/site-packages/esrally/rally.py", line 404, in race
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/lib/python3.4/site-packages/esrally/rally.py", line 425, in with_actor_system
    runnable(cfg)
  File "/usr/lib/python3.4/site-packages/esrally/rally.py", line 404, in <lambda>
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 417, in run
    raise e
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 414, in run
    pipeline(cfg)
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 78, in __call__
    self.target(cfg)
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 351, in benchmark_only
    return race(cfg, external=True)
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 303, in race
    raise exceptions.RallyError(result.message, result.cause)
esrally.exceptions.RallyError: ('Error in load generator [0]', '("Request returned an error. Error type: transport, Description: HTTPSConnectionPool(host=\'elasticsearch\', port=9200): Read timed out. (read timeout=10) (HTTPSConnectionPool(host=\'elasticsearch\', port=9200): Read timed out. (read timeout=10))", None)')
```

**Comment by danielmitterdorfer** [comment]
Thank you for your interest in Rally and providing such a thorough description. :)

If you do not provide `--client-options` Rally does indeed override the network timeout of the underlying Elasticsearch client from 10 seconds to 60 seconds (i.e. the default is as if you had provided ``--client-options="timeout:60"` yourself on the command line). However, if you override the default client options by specifying `--client-options` Rally will just use what you have passed it instead of applying any logic. As you have noted, Rally issues a warning to the console though to make you aware of the fact that you need to override this yourself by adding `timeout:60` if you want to. In summary, Rally intentionally uses what is provided by the user and we'd like to keep this behavior. Hope that makes sense now with my explanation above.

**Comment by VladMasarik** [comment]
@danielmitterdorfer Oh, okay. Could you explain why is there default value for `--client-options` arg? I assumed that there would be only one default value for `timeout` in all cases (with `--client-options` specified or not), but I was wrong. I would like to avoid this in the future, so what am I missing?

Also, thanks for such as quick response :)

**Comment by danielmitterdorfer** [comment]
> Could you explain why is there default value for --client-options arg?

The official Elasticsearch Python client (that Rally uses under the hood) defines a default read timeout of 10 seconds and back then I made the experience that it is too small for benchmarks because you can easily run into timeouts that might skew your results so we bumped it to 60 seconds by default for Rally (i.e. if you don't pass anything in `--client-options`). As soon as you pass `--client-options` we use the provided value verbatim and avoid applying any logic hence you need to provide `timeout` yourself in such cases.
