### ISSUE TITLE
esrally 1.2.1 can't use es 7.2.1 ssl for reporting

### ISSUE THREAD

**Issue by zqc0512** [elastic/rally#741]
esrally connect with ECE in my env
the log is

```
2019-08-13 03:03:30,728 -not-actor-/PID:107938 esrally.actor INFO Joining already running actor system with system base [multiprocTCPBase].
2019-08-13 03:03:30,730 ActorAddr-(T|:1900)/PID:107944 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 7, 3, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1565665410699'}] match requirements [{'coordinator': True}].
2019-08-13 03:03:30,730 ActorAddr-(T|:1900)/PID:107944 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 7, 3, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1565665410699'}] match requirements [{'coordinator': True}].
2019-08-13 03:03:30,920 -not-actor-/PID:107946 elasticsearch WARNING GET https://537dab8f6cd8411599733b8499f67cf7.xxx.xxx:9243/ [status:N/A request:0.013s]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/python3/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/python3/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 166, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/python3/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/python3/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
2019-08-13 03:03:30,933 -not-actor-/PID:107946 elasticsearch WARNING GET https://537dab8f6cd8411599733b8499f67cf7.soc.cnpc:9243/ [status:N/A request:0.011s]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/python3/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/python3/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
```

**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by ebadyano** [comment]
Thank you very much for your interest in Rally.

 I am able to use ES 7.2.1 as a metric store with esrally 1.2.1 without any errors. It looks like you are having issues with ssl certificate verification. You can use [datastore.ssl.verification_mode](https://esrally.readthedocs.io/en/stable/configuration.html?highlight=datastore.ssl.verification_mode) setting in Rally to disable verification.

As we reserve GitHub for verified bug reports, I am going to close this, but please feel free to move the discussion to a new topic in [forums](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
