### ISSUE TITLE
esrally can't running 1.3.0

### ISSUE THREAD

**Issue by zqc0512** [elastic/rally#770]
```
[root@xxxx ~]# esrally  --track=http_logs --challenge=append-index-only-with-ingest-pipeline  --car=24gheap --track-repository=zqc --offline --load-driver-hosts=xxxxx --target-hosts=309dc001bce946d0ab90b7082f61448c.xxx.xxx:9243 --pipeline=benchmark-only --client-options="timeout:80000,request_timeout:80000,use_ssl:true,verify_certs:false,basic_auth_user:'elastic',basic_auth_password:'xxxxx'"

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/


************************************************************************
************** WARNING: A dark dungeon lies ahead of you  **************
************************************************************************

Rally does not have control over the configuration of the benchmarked
Elasticsearch cluster.

Be aware that results may be misleading due to problems with the setup.
Rally is also not able to gather lots of metrics at all (like CPU usage
of the benchmarked cluster) or may even produce misleading metrics (like
the index size).

************************************************************************
****** Use this pipeline only if you are aware of the tradeoffs.  ******
*************************** Watch your step! ***************************
************************************************************************

[ERROR] Cannot race. Error in race control (('Cannot load track http_logs. List the available tracks with esrallyd list tracks.', None))

Getting further help:
*********************
* Check the log files in /root/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/1.3.0/
* Ask a question on the forum at https://discuss.elastic.co/c/elasticsearch/rally
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /root/.rally/logs.

-------------------------------
[INFO] FAILURE (took 0 seconds)
-------------------------------
[root@xxxxx~]# 
```

but runinng esrally list tracks can output

```

[root@xxxxx ~]# esrally list tracks

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[WARNING] No Internet connection detected. Automatic download of track data sets etc. is disabled.
[WARNING] Local changes in [.rally/benchmarks/tracks/default] prevent tracks update from remote. Please commit your changes.
Available tracks:

Name           Description                                                                                                                                                                        Documents    Compressed Size    Uncompressed Size    Default Challenge        All Challenges
-------------  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  -----------  -----------------  -------------------  -----------------------  ---------------------------------------------------------------------------------------------------------------------------
eventdata      This benchmark indexes HTTP access logs generated based sample logs from the elastic.co website using the generator available in https://github.com/elastic/rally-eventdata-track  20,000,000   755.1 MB           15.3 GB              append-no-conflicts      append-no-conflicts
geonames       POIs from Geonames                                                                                                                                                                 11,396,505   252.4 MB           3.3 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-sorted-no-conflicts,append-fast-with-conflicts
geopoint       Point coordinates from PlanetOSM                                                                                                                                                   60,844,404   481.9 MB           2.3 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-fast-with-conflicts
geopointshape  Point coordinates from PlanetOSM indexed as geoshapes                                                                                                                              60,844,404   470.5 MB           2.6 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-fast-with-conflicts
geoshape       Shapes from PlanetOSM                                                                                                                                                              60,523,283   13.4 GB            45.4 GB              append-no-conflicts      append-no-conflicts
http_logs      HTTP server log data                                                                                                                                                               247,249,096  1.2 GB             31.1 GB              append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-sorted-no-conflicts,append-index-only-with-ingest-pipeline,update
metricbeat     Metricbeat data                                                                                                                                                                    1,079,600    87.6 MB            1.2 GB               append-no-conflicts      append-no-conflicts
nested         StackOverflow Q&A stored as nested docs                                                                                                                                            11,203,029   663.1 MB           3.4 GB               nested-search-challenge  nested-search-challenge,index-only
noaa           Global daily weather measurements from NOAA                                                                                                                                        33,659,481   947.3 MB           9.0 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only
nyc_taxis      Taxi rides in New York in 2015                                                                                                                                                     165,346,692  4.5 GB             74.3 GB              append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-sorted-no-conflicts-index-only,update,append-ml
percolator     Percolator benchmark based on AOL queries                                                                                                                                          2,000,000    102.7 kB           104.9 MB             append-no-conflicts      append-no-conflicts
pmc            Full text benchmark with academic papers from PMC                                                                                                                                  574,199      5.5 GB             21.7 GB              append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-sorted-no-conflicts,append-fast-with-conflicts
so             Indexing benchmark using up to questions and answers from StackOverflow                                                                                                            36,062,278   8.9 GB             33.1 GB              append-no-conflicts      append-no-conflicts

-------------------------------
[INFO] SUCCESS (took 0 seconds)
-------------------------------
[root@xxxxx ~]# 
```

**Comment by zqc0512** [comment]
the log lis


```
2019-09-11 07:55:18,882 -not-actor-/PID:19723 esrally.rally INFO OS [posix.uname_result(sysname='Linux', nodename='f14cp-c1-es005', release='4.4.185-1.el7.elrepo.x86_64', version='#1 SMP Wed Jul 10 08:46:17 EDT 2019', machine='x86_64')]
2019-09-11 07:55:18,882 -not-actor-/PID:19723 esrally.rally INFO Python [namespace(_multiarch='x86_64-linux-gnu', cache_tag='cpython-37', hexversion=50791408, name='cpython', version=sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0))]
2019-09-11 07:55:18,882 -not-actor-/PID:19723 esrally.rally INFO Rally version [1.3.0]
2019-09-11 07:55:18,883 -not-actor-/PID:19723 esrally.utils.net INFO Connecting directly to the Internet (no proxy support).
2019-09-11 07:55:19,3 -not-actor-/PID:19723 esrally.rally INFO Actor system already running locally? [True]
2019-09-11 07:55:19,3 -not-actor-/PID:19723 esrally.actor INFO Joining already running actor system with system base [multiprocTCPBase].
2019-09-11 07:55:19,17 -not-actor-/PID:19723 esrally.racecontrol INFO User specified pipeline [benchmark-only].
2019-09-11 07:55:19,17 -not-actor-/PID:19723 esrally.racecontrol INFO Using configured hosts [{'host': '309dc001bce946d0ab90b7082f61448c.soc.cnpc', 'port': 9243}]
2019-09-11 07:55:19,17 -not-actor-/PID:19723 esrally.actor INFO Joining already running actor system with system base [multiprocTCPBase].
2019-09-11 07:55:19,19 ActorAddr-(T|:1900)/PID:14220 esrally.actor INFO Checking capabilities [{'coordinator': False, 'ip': '11.11.60.149', 'Convention Address.IPv4': '11.11.60.150:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 7, 3, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1568186471756'}] against requirements [{'coordinator': True}] failed.
2019-09-11 07:55:19,19 ActorAddr-(T|:1900)/PID:14220 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '11.11.60.150', 'Convention Address.IPv4': '11.11.60.150:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 7, 3, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1568186465245'}] match requirements [{'coordinator': True}].
2019-09-11 07:55:19,123 -not-actor-/PID:19723 esrally.racecontrol ERROR A benchmark failure has occurred
2019-09-11 07:55:19,124 -not-actor-/PID:19723 esrally.racecontrol INFO Telling benchmark actor to exit.
2019-09-11 07:55:19,126 -not-actor-/PID:19723 esrally.rally ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/esrally/rally.py", line 515, in dispatch_sub_command
    race(cfg)
  File "/usr/local/lib/python3.7/site-packages/esrally/rally.py", line 433, in race
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/lib/python3.7/site-packages/esrally/rally.py", line 461, in with_actor_system
    runnable(cfg)
  File "/usr/local/lib/python3.7/site-packages/esrally/rally.py", line 433, in <lambda>
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/lib/python3.7/site-packages/esrally/racecontrol.py", line 369, in run
    raise e
  File "/usr/local/lib/python3.7/site-packages/esrally/racecontrol.py", line 366, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.7/site-packages/esrally/racecontrol.py", line 78, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.7/site-packages/esrally/racecontrol.py", line 302, in benchmark_only
    return race(cfg, external=True)
  File "/usr/local/lib/python3.7/site-packages/esrally/racecontrol.py", line 254, in race
    raise exceptions.RallyError(result.message, result.cause)
esrally.exceptions.RallyError: ("Error in race control (('Cannot load track http_logs. List the available tracks with esrallyd list tracks.', None))", None)
```

**Comment by danielmitterdorfer** [comment]
Thank you very much for your interest in Rally.

Since this is a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests and allow other users to benefit from the discussion in the forum.

As such, I hope you don't mind that I close this.

**Comment by zqc0512** [comment]
in my network can't open discuss.elastic.co   please re open it. thanks.
@danielmitterdorfer
