### ISSUE TITLE
esrally  error

### ISSUE THREAD

**Issue by hengaiw** [elastic/rally#839]
2019-12-13 04:02:20,276 -not-actor-/PID:54887 esrally.rally INFO OS [posix.uname_result(sysname='Linux', nodename='master', release='4.14.0-115.el7.centos.a.0.2.aarch64', version='#1 SMP Tue Jul 30 03:30:56 EDT 2019', machine='aarch64')]
2019-12-13 04:02:20,277 -not-actor-/PID:54887 esrally.rally INFO Python [namespace(_multiarch='aarch64-linux-gnu', cache_tag='cpython-36', hexversion=50727152, name='cpython', version=sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0))]
2019-12-13 04:02:20,278 -not-actor-/PID:54887 esrally.rally INFO Rally version [1.2.1]
2019-12-13 04:02:20,278 -not-actor-/PID:54887 esrally.utils.net INFO Connecting directly to the Internet (no proxy support).
2019-12-13 04:02:21,469 -not-actor-/PID:54887 esrally.rally INFO Detected a working Internet connection.
2019-12-13 04:02:21,693 -not-actor-/PID:54887 esrally.rally INFO Actor system already running locally? [False]
2019-12-13 04:02:21,694 -not-actor-/PID:54887 esrally.actor INFO Starting actor system with system base [multiprocTCPBase] and capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900'}].
2019-12-13 04:02:21,730 -not-actor-/PID:54893 root INFO ++++ Actor System gen (3, 9) started, admin @ ActorAddr-(T|:1900)
2019-12-13 04:02:21,754 -not-actor-/PID:54887 esrally.racecontrol INFO User specified no pipeline. Automatically derived pipeline [from-distribution].
2019-12-13 04:02:21,755 -not-actor-/PID:54887 esrally.racecontrol INFO Setting default host to [127.0.0.1:39200]
2019-12-13 04:02:21,756 -not-actor-/PID:54887 esrally.actor INFO Joining already running actor system with system base [multiprocTCPBase].
2019-12-13 04:02:21,759 ActorAddr-(T|:1900)/PID:54893 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 8, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1576209741715'}] match requirements [{'coordinator': True}].
2019-12-13 04:02:21,760 ActorAddr-(T|:1900)/PID:54893 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 8, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1576209741715'}] match requirements [{'coordinator': True}].
2019-12-13 04:02:23,414 ActorAddr-(T|:39797)/PID:54895 esrally.utils.repo INFO Checking out [6] in [/home/es/.rally/benchmarks/tracks/default] for distribution version [6.0.0].
2019-12-13 04:02:23,428 ActorAddr-(T|:39797)/PID:54895 esrally.utils.repo INFO Rebasing on [6] in [/home/es/.rally/benchmarks/tracks/default] for distribution version [6.0.0].
2019-12-13 04:02:23,456 ActorAddr-(T|:39797)/PID:54895 esrally.track.loader INFO Reading track specification file [/home/es/.rally/benchmarks/tracks/default/pmc/track.json].
2019-12-13 04:02:23,544 ActorAddr-(T|:39797)/PID:54895 esrally.track.loader INFO Final rendered track for '/home/es/.rally/benchmarks/tracks/default/pmc/track.json' has been written to '/tmp/tmpjrfjqaqi.json'.
2019-12-13 04:02:23,563 ActorAddr-(T|:39797)/PID:54895 esrally.track.loader INFO Loading template [definition for index pmc in index.json].
2019-12-13 04:02:23,574 ActorAddr-(T|:39797)/PID:54895 esrally.track.loader INFO Using user-provided operation type [put-settings] for operation [put-settings].
2019-12-13 04:02:23,577 ActorAddr-(T|:39797)/PID:54895 esrally.metrics INFO Creating in-memory metrics store
2019-12-13 04:02:23,578 ActorAddr-(T|:39797)/PID:54895 esrally.metrics INFO Opening metrics store for trial timestamp=[20191213T040220Z], track=[pmc], challenge=[append-fast-with-conflicts], car=[['defaults']]
2019-12-13 04:02:23,578 ActorAddr-(T|:39797)/PID:54895 esrally.metrics INFO Creating file race store
2019-12-13 04:02:23,579 ActorAddr-(T|:39797)/PID:54895 esrally.actor INFO Asking mechanic to start the engine.
2019-12-13 04:02:23,580 ActorAddr-(T|:39797)/PID:54895 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 8, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1576209741715'}] match requirements [{'coordinator': True}].
2019-12-13 04:02:23,609 ActorAddr-(T|:44903)/PID:54912 esrally.actor INFO Received signal from race control to start engine.
2019-12-13 04:02:23,610 ActorAddr-(T|:44903)/PID:54912 esrally.metrics INFO Opening metrics store for trial timestamp=[20191213T040220Z], track=[pmc], challenge=[append-fast-with-conflicts], car=[['defaults']]
2019-12-13 04:02:25,37 ActorAddr-(T|:44903)/PID:54912 esrally.utils.repo INFO Checking out [6.0] in [/home/es/.rally/benchmarks/teams/default] for distribution version [6.0.0].
2019-12-13 04:02:25,51 ActorAddr-(T|:44903)/PID:54912 esrally.utils.repo INFO Rebasing on [6.0] in [/home/es/.rally/benchmarks/teams/default] for distribution version [6.0.0].
2019-12-13 04:02:25,82 ActorAddr-(T|:44903)/PID:54912 esrally.actor INFO Cluster consisting of [{'host': '127.0.0.1', 'port': 39200}] will be provisioned by Rally.
2019-12-13 04:02:25,82 ActorAddr-(T|:44903)/PID:54912 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 8, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1576209741715'}] match requirements [{}].
2019-12-13 04:02:25,108 ActorAddr-(T|:40265)/PID:54929 esrally.actor INFO Capabilities [{'coordinator': True, 'ip': '127.0.0.1', 'Convention Address.IPv4': '127.0.0.1:1900', 'Thespian ActorSystem Name': 'multiprocTCPBase', 'Thespian ActorSystem Version': 2, 'Thespian Watch Supported': True, 'Python Version': (3, 6, 8, 'final', 0), 'Thespian Generation': (3, 9), 'Thespian Version': '1576209741715'}] match requirements [{'coordinator': True}].
2019-12-13 04:02:25,131 ActorAddr-(T|:40917)/PID:54930 esrally.actor INFO Starting node(s) [0] on [127.0.0.1].
2019-12-13 04:02:25,135 ActorAddr-(T|:40917)/PID:54930 esrally.metrics INFO Opening metrics store for trial timestamp=[20191213T040220Z], track=[pmc], challenge=[append-fast-with-conflicts], car=[['defaults']]
2019-12-13 04:02:26,767 ActorAddr-(T|:40917)/PID:54930 esrally.utils.repo INFO Checking out [6.0] in [/home/es/.rally/benchmarks/teams/default] for distribution version [6.0.0].
2019-12-13 04:02:26,781 ActorAddr-(T|:40917)/PID:54930 esrally.utils.repo INFO Rebasing on [6.0] in [/home/es/.rally/benchmarks/teams/default] for distribution version [6.0.0].
2019-12-13 04:02:26,814 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.java_resolver INFO Allowed JDK versions are [8].
2019-12-13 04:02:26,941 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.java_resolver INFO Detected JDK with major version [8] in [/usr/lib/jvm/jre].
2019-12-13 04:02:26,942 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.supplier INFO Resolved download URL [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.tar.gz] for version [6.0.0]
2019-12-13 04:02:26,943 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.supplier INFO Skipping download for version [6.0.0]. Found an existing binary at [/home/es/.rally/benchmarks/distributions/elasticsearch-6.0.0.tar.gz].
2019-12-13 04:02:26,943 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Rally will delete the benchmark candidate after the benchmark
2019-12-13 04:02:26,944 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Preparing candidate locally in [/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install].
2019-12-13 04:02:26,945 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Unzipping /home/es/.rally/benchmarks/distributions/elasticsearch-6.0.0.tar.gz to /home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install
2019-12-13 04:02:27,394 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Deleting pre-bundled Elasticsearch configuration at [/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install/elasticsearch-6.0.0/config]
2019-12-13 04:02:27,395 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Reading config template file [/home/es/.rally/benchmarks/teams/default/cars/v1/vanilla/templates/config/elasticsearch.yml] and writing to [/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install/elasticsearch-6.0.0/config/elasticsearch.yml].
2019-12-13 04:02:27,414 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Reading config template file [/home/es/.rally/benchmarks/teams/default/cars/v1/vanilla/templates/config/jvm.options] and writing to [/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install/elasticsearch-6.0.0/config/jvm.options].
2019-12-13 04:02:27,423 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.provisioner INFO Reading config template file [/home/es/.rally/benchmarks/teams/default/cars/v1/vanilla/templates/config/log4j2.properties] and writing to [/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install/elasticsearch-6.0.0/config/log4j2.properties].
2019-12-13 04:02:27,430 ActorAddr-(T|:40917)/PID:54930 esrally.utils.process INFO Killing all processes which match [java], [elasticsearch] and [/home/es/.rally/benchmarks/races]
2019-12-13 04:02:27,552 ActorAddr-(T|:40917)/PID:54930 esrally.utils.process INFO Killing lingering process with PID [54700] and command line [['/usr/lib/jvm/jre/bin/java', '-Xms1g', '-Xmx1g', '-XX:+UseConcMarkSweepGC', '-XX:CMSInitiatingOccupancyFraction=75', '-XX:+UseCMSInitiatingOccupancyOnly', '-XX:+AlwaysPreTouch', '-server', '-Xss1m', '-Djava.awt.headless=true', '-Dfile.encoding=UTF-8', '-Djna.nosys=true', '-XX:-OmitStackTraceInFastThrow', '-Dio.netty.noUnsafe=true', '-Dio.netty.noKeySetOptimization=true', '-Dio.netty.recycler.maxCapacityPerThread=0', '-Dlog4j.shutdownHookEnabled=false', '-Dlog4j2.disable.jmx=true', '-XX:+HeapDumpOnOutOfMemoryError', '-XX:HeapDumpPath=/home/es/.rally/benchmarks/races/2019-12-13-04-01-05/rally-node-0/heapdump', '-XX:+ExitOnOutOfMemoryError', '-Des.path.home=/home/es/.rally/benchmarks/races/2019-12-13-04-01-05/rally-node-0/install/elasticsearch-6.0.0', '-Des.path.conf=/home/es/.rally/benchmarks/races/2019-12-13-04-01-05/rally-node-0/install/elasticsearch-6.0.0/config', '-cp', '/home/es/.rally/benchmarks/races/2019-12-13-04-01-05/rally-node-0/install/elasticsearch-6.0.0/lib/*', 'org.elasticsearch.bootstrap.Elasticsearch']].
2019-12-13 04:02:28,558 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.java_resolver INFO Allowed JDK versions are [8].
2019-12-13 04:02:28,692 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.java_resolver INFO Detected JDK with major version [8] in [/usr/lib/jvm/jre].
2019-12-13 04:02:28,693 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO Starting node [rally-node-0] based on car [defaults].
2019-12-13 04:02:28,804 ActorAddr-(T|:40917)/PID:54930 esrally.utils.process INFO b'openjdk version "1.8.0_232"\n'
2019-12-13 04:02:28,805 ActorAddr-(T|:40917)/PID:54930 esrally.utils.process INFO b'OpenJDK Runtime Environment (build 1.8.0_232-b09)\n'
2019-12-13 04:02:28,806 ActorAddr-(T|:40917)/PID:54930 esrally.utils.process INFO b'OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)\n'
2019-12-13 04:02:28,812 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO Setting [-XX:+ExitOnOutOfMemoryError] to detect out of memory errors during the benchmark.
2019-12-13 04:02:30,705 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:30,703][INFO ][o.e.n.Node               ] [rally-node-0] initializing ...
2019-12-13 04:02:30,835 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:30,834][INFO ][o.e.e.NodeEnvironment    ] [rally-node-0] using [1] data paths, mounts [[/home (/dev/mapper/centos-home)]], net usable_space [805.3gb], net total_space [838.6gb], types [xfs]
2019-12-13 04:02:30,835 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:30,835][INFO ][o.e.e.NodeEnvironment    ] [rally-node-0] heap size [989.8mb], compressed ordinary object pointers [true]
2019-12-13 04:02:30,837 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:30,837][INFO ][o.e.n.Node               ] [rally-node-0] node name [rally-node-0], node ID [x18iGOfLRFiqTBJBWCO73A]
2019-12-13 04:02:30,838 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:30,838][INFO ][o.e.n.Node               ] [rally-node-0] version[6.0.0], pid[55154], build[8f0685b/2017-11-10T18:41:22.859Z], OS[Linux/4.14.0-115.el7.centos.a.0.2.aarch64/aarch64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_232/25.232-b09]
2019-12-13 04:02:30,838 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:30,838][INFO ][o.e.n.Node               ] [rally-node-0] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/heapdump, -XX:+ExitOnOutOfMemoryError, -Des.path.home=/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install/elasticsearch-6.0.0, -Des.path.conf=/home/es/.rally/benchmarks/races/2019-12-13-04-02-20/rally-node-0/install/elasticsearch-6.0.0/config]
2019-12-13 04:02:32,460 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,460][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [aggs-matrix-stats]
2019-12-13 04:02:32,461 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,460][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [analysis-common]
2019-12-13 04:02:32,461 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,460][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [ingest-common]
2019-12-13 04:02:32,462 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,461][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [lang-expression]
2019-12-13 04:02:32,462 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,461][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [lang-mustache]
2019-12-13 04:02:32,463 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,461][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [lang-painless]
2019-12-13 04:02:32,463 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,461][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [parent-join]
2019-12-13 04:02:32,464 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,462][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [percolator]
2019-12-13 04:02:39,428 ActorAddr-(T|:39797)/PID:54895 esrally.actor INFO Received a benchmark failure from [ActorAddr-(T|:44903)] and will forward it now.
2019-12-13 04:02:32,464 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,462][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [reindex]
2019-12-13 04:02:39,432 -not-actor-/PID:54887 esrally.racecontrol ERROR A benchmark failure has occurred
2019-12-13 04:02:39,432 -not-actor-/PID:54887 esrally.racecontrol INFO Telling benchmark actor to exit.
2019-12-13 04:02:32,465 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,462][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [repository-url]
2019-12-13 04:02:39,434 ActorAddr-(T|:39797)/PID:54895 esrally.actor INFO BenchmarkActor received unknown message [ActorExitRequest] (ignoring).
2019-12-13 04:02:32,465 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,462][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [transport-netty4]
2019-12-13 04:02:39,436 ActorAddr-(T|:44903)/PID:54912 esrally.actor INFO MechanicActor#receiveMessage unrecognized(msg = [<class 'thespian.actors.ActorExitRequest'>] sender = [ActorAddr-(T|:39797)])
2019-12-13 04:02:32,465 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,463][INFO ][o.e.p.PluginsService     ] [rally-node-0] loaded module [tribe]
2019-12-13 04:02:39,439 ActorAddr-(T|:40265)/PID:54929 esrally.actor INFO mechanic.Dispatcher#receiveMessage unrecognized(msg = [<class 'thespian.actors.ActorExitRequest'>] sender = [ActorAddr-(T|:44903)])
2019-12-13 04:02:32,466 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:32,464][INFO ][o.e.p.PluginsService     ] [rally-node-0] no plugins loaded
2019-12-13 04:02:34,833 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:34,833][INFO ][o.e.d.DiscoveryModule    ] [rally-node-0] using discovery type [zen]
2019-12-13 04:02:39,445 ActorAddr-(T|:40265)/PID:54929 esrally.actor INFO mechanic.Dispatcher#receiveMessage unrecognized(msg = [<class 'thespian.actors.ChildActorExited'>] sender = [ActorAddr-(T|:40917)])
2019-12-13 04:02:35,701 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:35,700][INFO ][o.e.n.Node               ] [rally-node-0] initialized
2019-12-13 04:02:39,449 ActorAddr-(T|:44903)/PID:54912 esrally.actor ERROR Child actor exited with [ChildActorExited:ActorAddr-(T|:40265)] while in status [starting].
2019-12-13 04:02:35,702 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:35,701][INFO ][o.e.n.Node               ] [rally-node-0] starting ...
2019-12-13 04:02:36,44 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:36,044][INFO ][o.e.t.TransportService   ] [rally-node-0] publish_address {127.0.0.1:39300}, bound_addresses {127.0.0.1:39300}
2019-12-13 04:02:39,135 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:39,134][INFO ][o.e.c.s.MasterService    ] [rally-node-0] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {rally-node-0}{x18iGOfLRFiqTBJBWCO73A}{jgsh3GZjQ_OYFEh8ToGwZA}{127.0.0.1}{127.0.0.1:39300}
2019-12-13 04:02:39,455 ActorAddr-(T|:39797)/PID:54895 esrally.actor INFO BenchmarkActor received unknown message [ChildActorExited:ActorAddr-(T|:44903)] (ignoring).
2019-12-13 04:02:39,143 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:39,142][INFO ][o.e.c.s.ClusterApplierService] [rally-node-0] new_master {rally-node-0}{x18iGOfLRFiqTBJBWCO73A}{jgsh3GZjQ_OYFEh8ToGwZA}{127.0.0.1}{127.0.0.1:39300}, reason: apply cluster state (from master [master {rally-node-0}{x18iGOfLRFiqTBJBWCO73A}{jgsh3GZjQ_OYFEh8ToGwZA}{127.0.0.1}{127.0.0.1:39300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
2019-12-13 04:02:39,226 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:39,226][INFO ][o.e.h.n.Netty4HttpServerTransport] [rally-node-0] publish_address {127.0.0.1:39200}, bound_addresses {127.0.0.1:39200}
2019-12-13 04:02:39,227 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO rally-node-0 (stdout): [2019-12-13T12:02:39,226][INFO ][o.e.n.Node               ] [rally-node-0] started
2019-12-13 04:02:39,228 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO [rally-node-0] has successfully started.
2019-12-13 04:02:39,228 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO Started node [rally-node-0] with PID [55154].
2019-12-13 04:02:39,229 ActorAddr-(T|:40917)/PID:54930 esrally.mechanic.launcher INFO Attaching telemetry devices to node [rally-node-0].
2019-12-13 04:02:39,294 ActorAddr-(T|:40917)/PID:54930 esrally.actor ERROR Cannot process message [<esrally.mechanic.mechanic.StartNodes object at 0xffffa8a862b0>]
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 576, in receiveMsg_StartNodes
    nodes = self.mechanic.start_engine()

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 712, in start_engine
    self.nodes = self.launcher.start(node_configs)

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/launcher.py", line 309, in start
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/launcher.py", line 309, in <listcomp>
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/launcher.py", line 341, in _start_node
    t.attach_to_node(node)

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/telemetry.py", line 75, in attach_to_node
    device.attach_to_node(node)

  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/telemetry.py", line 933, in attach_to_node
    self.metrics_store.add_meta_info(metrics.MetaInfoScope.node, node.node_name, "cpu_model", sysstats.cpu_model())

  File "/usr/local/lib/python3.6/site-packages/esrally/utils/sysstats.py", line 48, in cpu_model
    return cpuinfo.get_cpu_info()["brand"] if cpuinfo_available else "Unknown"

KeyError: 'brand'

2019-12-13 04:02:42,437 -not-actor-/PID:54887 esrally.rally INFO Attempting to shutdown internal actor system.
2019-12-13 04:02:42,440 -not-actor-/PID:54894 root INFO ActorSystem Logging Shutdown
2019-12-13 04:02:42,461 -not-actor-/PID:54893 root INFO ---- Actor System shutdown
2019-12-13 04:02:42,462 -not-actor-/PID:54887 esrally.rally INFO Actor system is still running. Waiting...
2019-12-13 04:02:43,464 -not-actor-/PID:54887 esrally.rally INFO Shutdown completed.
2019-12-13 04:02:43,464 -not-actor-/PID:54887 esrally.rally ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/esrally/rally.py", line 514, in dispatch_sub_command
    race(cfg)
  File "/usr/local/lib/python3.6/site-packages/esrally/rally.py", line 432, in race
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/lib/python3.6/site-packages/esrally/rally.py", line 460, in with_actor_system
    runnable(cfg)
  File "/usr/local/lib/python3.6/site-packages/esrally/rally.py", line 432, in <lambda>
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/lib/python3.6/site-packages/esrally/racecontrol.py", line 427, in run
    raise e
  File "/usr/local/lib/python3.6/site-packages/esrally/racecontrol.py", line 424, in run
    pipeline(cfg)
  File "/usr/local/lib/python3.6/site-packages/esrally/racecontrol.py", line 79, in __call__
    self.target(cfg)
  File "/usr/local/lib/python3.6/site-packages/esrally/racecontrol.py", line 344, in from_distribution
    return race(cfg, distribution=True)
  File "/usr/local/lib/python3.6/site-packages/esrally/racecontrol.py", line 304, in race
    raise exceptions.RallyError(result.message, result.cause)
esrally.exceptions.RallyError: (KeyError('brand',), 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 576, in receiveMsg_StartNodes\n    nodes = self.mechanic.start_engine()\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/mechanic.py", line 712, in start_engine\n    self.nodes = self.launcher.start(node_configs)\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/launcher.py", line 309, in start\n    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/launcher.py", line 309, in <listcomp>\n    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/launcher.py", line 341, in _start_node\n    t.attach_to_node(node)\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/telemetry.py", line 75, in attach_to_node\n    device.attach_to_node(node)\n  File "/usr/local/lib/python3.6/site-packages/esrally/mechanic/telemetry.py", line 933, in attach_to_node\n    self.metrics_store.add_meta_info(metrics.MetaInfoScope.node, node.node_name, "cpu_model", sysstats.cpu_model())\n  File "/usr/local/lib/python3.6/site-packages/esrally/utils/sysstats.py", line 48, in cpu_model\n    return cpuinfo.get_cpu_info()["brand"] if cpuinfo_available else "Unknown"\nKeyError: \'brand\'\n')

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Rally. According to this output, your Rally version is 1.2.1 and this problem has been fixed in https://github.com/elastic/rally/pull/719 which is included in Rally 1.3.0.  Hence, closing as only an upgrade is required to fix this. In the future, please format input for readability.
