### ISSUE TITLE
Support .gzipped benchmark data

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#87]
Currently we only support .zip and .bz2. We should maybe also support gzipped data sets.

Currently, we get the following trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 9, in <module>
    load_entry_point('esrally==0.2.1.dev0', 'console_scripts', 'esrally')()
  File "/home/dm/rally/esrally/rally.py", line 238, in main
    success = race_control.start(subcommand)
  File "/home/dm/rally/esrally/racecontrol.py", line 260, in start
    pipeline.run(t)
  File "/home/dm/rally/esrally/racecontrol.py", line 88, in run
    step.run(track)
  File "/home/dm/rally/esrally/racecontrol.py", line 27, in run
    self.command(self.ctx, track)
  File "/home/dm/rally/esrally/racecontrol.py", line 116, in prepare_track
    ctx.marshal.setup(track)
  File "/home/dm/rally/esrally/track/track.py", line 346, in setup
    unzipped_data_set_path = self._unzip(data_set_path)
  File "/home/dm/rally/esrally/track/track.py", line 406, in _unzip
    io.unzip(data_set_path, io.dirname(data_set_path))
  File "/home/dm/rally/esrally/utils/io.py", line 68, in unzip
    raise RuntimeError("Unsupported file extension '%s'. Cannot unzip '%s'" % (extension, zip_name))
RuntimeError: Unsupported file extension '.gz'. Cannot unzip '/home/dm/rally-test/data/logging/logs.json.gz'
```

**Comment by danielmitterdorfer** [comment]
Closed by #88
