### ISSUE TITLE
Cannot race. 'NoneType' object has no attribute 'read_bytes'

### ISSUE THREAD

**Issue by steevegldev** [elastic/rally#888]
**Rally version** (get with `esrally --version`): esrally 1.4.0

**Invoked command**:  esrally --distribution-version=7.5.2 --track=eventdata --challenge=append-no-conflicts

**Configuration file (located in `~/.rally/rally.ini`))**: 
```[meta]
config.version = 17

[system]
env.name = local

[node]
root.dir = /home/user/.rally/benchmarks
src.root.dir = /home/user/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /home/user/.rally/benchmarks/data

[reporting]
datastore.type = elasticsearch
datastore.host = ********.eastus2.azure.elastic-cloud.com
datastore.port = 9243
datastore.secure = True
datastore.user = elastic
datastore.password = *********

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true
```

**JVM version**:
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**OS version**:
Linux DESKTOP 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Run `esrally --distribution-version=7.5.2 --track=eventdata --challenge=append-no-conflicts`
 2. Got: 
```[INFO] Preparing for race ...
[ERROR] Cannot race. 'NoneType' object has no attribute 'read_bytes'
        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/mechanic.py", line 565, in receiveMsg_StartNodes
    self.mechanic.start_engine()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/mechanic.py", line 680, in start_engine
    self.nodes = self.launcher.start(self.node_configs)
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/launcher.py", line 126, in start
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/launcher.py", line 126, in <listcomp>
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/launcher.py", line 160, in _start_node
    t.attach_to_node(node)
  File "/usr/local/lib/python3.6/dist-packages/esrally/telemetry.py", line 65, in attach_to_node
    device.attach_to_node(node)
  File "/usr/local/lib/python3.6/dist-packages/esrally/telemetry.py", line 750, in attach_to_node
    self.read_bytes = disk_start.read_bytes
AttributeError: 'NoneType' object has no attribute 'read_bytes'


Getting further help:
*********************
* Check the log files in /home/user/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/1.4.0/
* Ask a question on the forum at https://discuss.elastic.co/c/elasticsearch/rally
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /home/user/.rally/logs.

--------------------------------
[INFO] FAILURE (took 21 seconds)
--------------------------------```

**Provide logs (if relevant)**:

**Comment by dliappis** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch/Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by steevegldev** [comment]
Related to https://github.com/giampaolo/psutil/issues/1251

Not compatible with WSL.
